### ISSUE TITLE
Causes completion menu to open all the time

### ISSUE THREAD

**Issue by brendanjerwin** [zchee/deoplete-go#1]
The `g:deoplete#auto_completion_start_length` doesn't seem to work with this plugin. I hacked in a small change that seems to work, what do you think?

https://github.com/brendanjerwin/deoplete-go/blob/master/rplugin/python3/deoplete/sources/go.py#L13

**Comment by nothingelsematters7** [comment]
The same happens for me

**Comment by nothingelsematters7** [comment]
@brendanjerwin your fix seems to work good. May be create PR?

**Comment by nhooyr** [comment]
i opened pull request #2 to address this

**Comment by nhooyr** [comment]
@zchee this should be closed because of the merge of #2

**Comment by zchee** [comment]
@nhooyr Thanks mention :)

Close.
