### ISSUE TITLE
How disable deoplete output

### ISSUE THREAD

**Issue by ghost** [zchee/deoplete-go#103]
If just output deoplete-go candicates, what do we  need to do?

**Comment by Shougo** [comment]
What is the output?
Please upload the screenshot.

**Comment by ghost** [comment]
![_ _20170714095717](https://user-images.githubusercontent.com/20379044/28195574-aefd29ec-687d-11e7-8a84-70c2f00c2f0e.png)
don't output first candidate, what should do?
@Shougo

**Comment by Shougo** [comment]
This is not deoplete go problem.

```vim
call deoplete#custom#set('go', 'rank', 9999)
```
