### ISSUE TITLE
Complete on packages not yet imported

### ISSUE THREAD

**Issue by desdic** [zchee/deoplete-go#104]
Hi,

I can't seem to get deoplete-go to complete om stdlibs except if the package is in the import list like so

example:

net. does not give a completion

import "fmt"
fmt. gives autocompletion

is there a feature I'm missing ?

**Comment by Shougo** [comment]
I don't understand it.
Please upload the sample codes.

**Comment by desdic** [comment]
Ah sorry .. I have this example:

```
package main

import "fmt"

func main() {
	fmt.Println("helloworld")
}
```

Now if I type fmt dot it will give me all the functions that fmt provies (This works as it should). But if I type for example 'net' it does not even suggest the package net. Is there a way to make deoplete-go to suggest nonimported packages?
I have the following in my neovim config:

```vim
let g:deoplete#enable_at_startup = 1                                                                                                           
let g:deoplete#enable_smart_case = 1                                                                                                           
let g:deoplete#disable_auto_complete = 0 " set to 1 if you want to disable autocomplete                                                        
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif                                                                       
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'                                                                                
let g:deoplete#sources#go#package_dot = 1                                                                                                      
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']                                                             
let g:deoplete#sources#go#use_cache = 1                                                                                                        
let g:deoplete#sources#go#json_directory = '~/.cache/deoplete/go'
```

I'm also using vim-go with these options:
```vim
let g:go_gocode_propose_builtins = 1                                                                                                           
let g:go_gocode_unimported_packages = 1
```

neovim: NVIM v0.2.0

**Comment by Shougo** [comment]
> Is there a way to make deoplete-go to suggest nonimported packages?

golang can call non imported packages?
I think it is not.  So it seems feature.

**Comment by Shougo** [comment]
It seems golang and gocode feature.

**Comment by Shougo** [comment]
https://github.com/fatih/vim-go/blob/837143b7235ebabc01b8c06af7381df4cb7b345b/autoload/go/complete.vim#L71

@zchee vim-go supports the feature.  deoplete-go can support it?

@desdic 
> I'm also using vim-go with these options:

This is just vim-go configuration.
deoplete-go does not use vim-go configuration.

**Comment by Shougo** [comment]
https://github.com/fatih/vim-go/pull/1084

> gocode recently added support for unimported packages.
> nsf/gocode@57b3fab

Hm

**Comment by zchee** [comment]
@Shougo Short answer is No. vim-go is like Go language IDE for Vim, but deoplete-go(and droplets) is just completion engine.
So, I think implements that config is overkill.

**Comment by Shougo** [comment]
I don't know why the feature is needed.
The other completion engines do not support the feature.

**Comment by desdic** [comment]
Oh .. I just tried vscode and that seem to have that feature and though it was a nice feature .. but thanks for the quick answer :+1:
