### ISSUE TITLE
completion does not work when paste enabled

### ISSUE THREAD

**Issue by kthommandra** [zchee/deoplete-go#109]
This could be a deoplete issue and not a deoplete-go issue. I'm not sure but in my environment I can recreate this 100% 

## Environment Information

 * deoplete version(SHA1):
ac4e8b56115f1bdcda5401ea7eeb1b5a3046ebe3
 * deoplete-go (SHA1):
05f617928a1522c16ed43373ec1b6db145b28720
 * OS:
debian buster/sid 4.9.36-moby
 * neovim version:
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-seW4CW/neovim-0.2.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-seW4CW/neovim-0.2.0/build/config -I/build/neovim-seW4CW/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-seW4CW/neovim-0.2.0/build/src/nvim/auto -I/build/neovim-seW4CW/neovim-0.2.0/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
 * `:CheckHealth` result(neovim ver.0.1.5-452+):
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers will not work.
    - SUGGESTIONS:
      - :help clipboard

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    python2 not found in search path or not executable.
    python2.7 not found in search path or not executable.
    python2.6 not found in search path or not executable.
    /usr/bin/python is Python 3.5 and cannot provide Python 2.
  - ERROR: Python provider error
    - SUGGESTIONS:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.5 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python3 version: 3.5.4
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - SUGGESTIONS:
      - Install Ruby and verify that `ruby` and `gem` commands work.
## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim

call plug#begin('~/.config/nvim/plugged')

"Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins'}
Plug 'zchee/deoplete-go', { 'do': 'make'}

let g:deoplete#enable_at_startup = 1

"disable paste to get completion working again
set paste

call plug#end()
```

## The reproduce ways from neovim starting (Required!)

 1. with "set paste" disabled, completion works fine
 2. with "set paste" enabled, completion doesn't work

**Comment by kthommandra** [comment]
Debug logs for working and not-working conditions

[logwork.txt](https://github.com/zchee/deoplete-go/files/1269187/logwork.txt)
[lognotwork.txt](https://github.com/zchee/deoplete-go/files/1269186/lognotwork.txt)

**Comment by Shougo** [comment]
This is feature.
Please execute `:help 'paste'`.
It is not for the completion feature.
