### ISSUE TITLE
'[deoplete] gocode binary not found' on windows

### ISSUE THREAD

**Issue by jsfaint** [zchee/deoplete-go#112]
My environment is windows 10 with neovim 0.2.1 64bit

Use the default setting of deoplete-go, it shows error message below
![deoplete-go_panic_on_windows](https://user-images.githubusercontent.com/571829/32763709-40c9b312-c93c-11e7-9ef0-5b4202865387.png)

It looks like the issue is in `find_gocode_binary()`, I have a quick fix for this issue
```diff
diff --git a/rplugin/python3/deoplete/sources/deoplete_go.py b/rplugin/python3/deoplete/sources/deoplete_go.py
index d9870dc..9cef093 100644
--- a/rplugin/python3/deoplete/sources/deoplete_go.py
+++ b/rplugin/python3/deoplete/sources/deoplete_go.py
@@ -276,7 +276,10 @@ class Source(Base):
             else:
                 raise
         except Exception:
-            return self.find_binary_path('gocode')
+            if platform.system().lower() == 'windows':
+                return self.find_binary_path('gocode.exe')
+            else:
+                return self.find_binary_path('gocode')

     def find_binary_path(self, path):
```

After using the patch, it works now
![image](https://user-images.githubusercontent.com/571829/32763812-fe74a55c-c93c-11e7-8838-3116b3f2e3d7.png)

**Comment by Shougo** [comment]
It should be fixed.  OK.

@jsfaint Can you send the PR?

**Comment by jsfaint** [comment]
@Shougo The PR is sent, thanks 😄

**Comment by Shougo** [comment]
Thanks.
