### ISSUE TITLE
Extend documentation installing deoplete-go without Vim package manager

### ISSUE THREAD

**Issue by the42** [zchee/deoplete-go#121]
Your documentation reads

    So, If you use Plugin manager supported build process, set make commmand.

What to do if I do not use a plugin manager (I am using Vim8 packages)

I downloaded (cloned the repo) and called `make`. I think this succeeded. What to copy where to make `deoplete` Golang-completion aware?

**Comment by Shougo** [comment]
> What to do if I do not use a plugin manager (I am using Vim8 packages)

If you use Vim8 packages, why don't you know plugin installation?

You should study Vim8 packages feature.

I think it is not plugin documentation work.

**Comment by Shougo** [comment]
I have read other plugin documentation, but I don't know for Vim package manager documentation.
It is for advanced user feature.

**Comment by the42** [comment]
Ok I figured out myself and leave it here for others.

Those not using a package manger but solely relying on Vim8 package features can install this plugin easily too.

0. Have the build-essentials met (not covered, but building deoplete-go requires a working go environment, python and a C-compiler) and deoplete already installed and working. This is no different from other package-manager supported ways to install this plugin
1. Clone the repo preferably into .config/nvim/pack/plugins/start/ like `git clone https://github.com/zchee/deoplete-go.git ~/.config/nvim/pack/plugins/start/`
2. cd into the cloned repo and simply call `make`. If all dependencies of 0. are met,
3. you are done :)
