### ISSUE TITLE
Doesn't work with mdempsky/gocode

### ISSUE THREAD

**Issue by joshuarubin** [zchee/deoplete-go#123]
https://github.com/nsf/gocode states:

> IMPORTANT: consider switching to https://github.com/mdempsky/gocode if you have problems starting with Go version 1.10, due to changes in binary packages architecture (introduction of package cache) I'm not going to adjust gocode for it for quite some time. There is a higher chance that fork under the given link will have some solution to the problem sooner or later.

However, this plugin doesn't work with [mdempsky/gocode](https://github.com/mdempsky/gocode)

**Comment by Shougo** [comment]
deoplete-go depends on nsf/gocode.
Pull request is wellcome.

**Comment by Shougo** [comment]
No problem for me.
