### ISSUE TITLE
[deoplete] gocode decode error

### ISSUE THREAD

**Issue by nettrino** [zchee/deoplete-go#124]
Hello, 

I get `gocode decode error` when simply typing `fmt`. No other information is printed in the error. Subsequently if I type `.` the suggestions appear as usual. Looks like [`stdout_data`](https://github.com/zchee/deoplete-go/blob/513ae17f1bd33954da80059a21c128a315726a81/rplugin/python3/deoplete/sources/deoplete_go.py#L228) is empty? Also if `stdout_data` is empty this `Exception` will be thrown and then we will have another error inside the Exception handler's [`decode()`](https://github.com/zchee/deoplete-go/blob/513ae17f1bd33954da80059a21c128a315726a81/rplugin/python3/deoplete/sources/deoplete_go.py#L237)

Also it would be useful to add the actual error when throwing an [`Exception`](https://github.com/zchee/deoplete-go/blob/513ae17f1bd33954da80059a21c128a315726a81/rplugin/python3/deoplete/sources/deoplete_go.py#L235), as well as add a config option for users to suppress errors overall?

(Edit: switching to [mdempsky's gocode](https://github.com/mdempsky/gocode) and removing the `/tmp/gocode-daemon` file on my system fixes the errors for me, but the issue seems valid still)

**Comment by Shougo** [comment]
@nettrino Please test https://github.com/zchee/deoplete-go/pull/125.

> Also it would be useful to add the actual error when throwing an Exception, as well as add a config option for users to suppress errors overall?

`:help deoplete-source-attribute-is_silent`
