### ISSUE TITLE
Autocompletion Works for Standard Lib, Doesn't for Other Packages

### ISSUE THREAD

**Issue by naftulikay** [zchee/deoplete-go#128]
### Operating System

I am on Ubuntu 16.04 running kernel 4.13.0-41-generic. 

### NeoVim

I am using NeoVim's package repository and I'm using NeoVim 0.2.2 which is the latest at the time of writing:

```
$ nvim --version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I also have the requisite Python libraries installed for NeoVim, and here's some configuration regarding Python on my machine:

```
$ pip2 show neovim | head -2
Name: neovim
Version: 0.2.6
$ pip3 show neovim | head -2
Name: neovim
Version: 0.2.6
naftuli@airsong:~/devel/src/github.com/naftulikay/gobender$ python --version
Python 2.7.12
$ python3 --version
Python 3.5.2
```

### Vim Plug

I am using vim-plug as a package manager and I am running the latest version in master at this point in time, commit [`e0ca037`](https://github.com/junegunn/vim-plug/commit/e0ca037a4fe6d3b2d0b85ceec9b69670cc9db2bc):

```
$ curl -sSL -o ~/.local/share/nvim/site/autoload/plug.vim \
    https://github.com/junegunn/vim-plug/blob/e0ca037a4fe6d3b2d0b85ceec9b69670cc9db2bc/plug.vim
```

### Go

My Go environment variables:

```
$ echo $GOPATH
/home/naftuli/devel
$ echo $GOROOT
/usr/local/go
```

Here's my version info:

```
$ go version
go version go1.10.2 linux/amd64
```

My current working directory is `~/devel/src/github.com/naftulikay/gobender`.

### Vim

To keep everything honest, I have wiped my plugs directory:

```
$ rm -fr ~/.local/share/nvim/plugged/*
```

This is my barebones configuration file:

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-go', { 'do': 'make' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

set completeopt+=noselect

let g:python3_host_skip_check = 1

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#gocode_binary = $HOME.'/devel/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
```

I am starting vim with `vim -u barebones.vim +PlugInstall`, and all of the dependencies install correctly.

### Go

Here is the layout of my project:

```
$ tree -L 2 ~/devel/src/github.com/naftulikay/gobender/
/home/naftuli/devel/src/github.com/naftulikay/gobender/
├── ansible.cfg
├── barebones.vim
├── cmd
│   └── root.go
├── gobender
├── main.go
├── README.md
├── requirements.yml
├── Vagrantfile
└── vagrant.yml

1 directory, 9 files
```

Here is `./main.go`:

```go
package main

import "github.com/naftulikay/gobender/cmd"

func main() {
	cmd.Execute()
}
```

Here is `./cmd/root.go`:

```go
package cmd

import (
	"fmt"
)

func Execute() {
	fmt.Println("unacceptable")
}

func WarAndAnger() {
	fmt.Println("I stg if this keeps happening")
}
```

These compile fine with `go build`.

## Results

I enter my editor via `vim -u barebones.vim main.go`:

![screenshot from 2018-06-28 13 31 30](https://user-images.githubusercontent.com/347571/42059239-9bfa3c00-7ad7-11e8-9dd2-dd6508aca84b.png)

If I attempt to use a built-in package, I see completion work just fine:

![screenshot from 2018-06-28 13 32 35](https://user-images.githubusercontent.com/347571/42059284-bb797df2-7ad7-11e8-9c36-076da2648386.png)

If I attempt to complete on my own local source code, nothing happens:

![screenshot from 2018-06-28 13 33 21](https://user-images.githubusercontent.com/347571/42059318-d6f70478-7ad7-11e8-9322-4f993d4da809.png)

It should complete `WarAndAnger`.

I cannot resolve why it can't import local files but that it can import system files and complete for them.

Is there something I'm doing wrong?

**Comment by Shougo** [comment]
`let g:python3_host_skip_check = 1` does not work.
You should read `:help g:python3_host_prog`.

**Comment by Shougo** [comment]
What is your `$GOPATH` value in Vim?
deoplete-go completes the packages under `$GOPATH`.

I think your current path is not under `$GOPATH`.

**Comment by Shougo** [comment]
Reproduced.  But gocode does support the completion?
I don't know about it.
Please check it.

**Comment by naftulikay** [comment]
@Shougo so you were also able to see the issue, or were you unable to reproduce?

How should I test gocode on the completion?

My project lives at `/home/naftuli/devel/src/github.com/naftulikay/gobender`. If I `echo $GOPATH` from within Vim, I see `/home/naftuli/devel`.

I can provide a full VM environment that should isolate all of the variable things and provide a consistent environment. My repository is located at [naftulikay/gobender](https://github.com/naftulikay/gobender) and my simple `barebones.vim` is located there. Would that be useful?

**Comment by methane** [comment]
Which gocode do you use? nsf? mdempsky?
Have you tried https://github.com/mdempsky/gocode#debugging ?

**Comment by Shougo** [comment]
Please read the issue.
https://github.com/mdempsky/gocode/issues/32

**Comment by naftulikay** [comment]
@Shougo thank you so much, it has taken some time, but I got it working.

This is my final config:

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'mdempsky/gocode', { 'rtp': 'nvim', 'do': '~/.local/share/nvim/plugged/gocode/nvim/symlink.sh' }
Plug 'zchee/deoplete-go', { 'do': 'make' }

call plug#end()

set completeopt+=noselect

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#gocode_binary = $HOME.'/devel/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
let g:deoplete#sources#go#source_importer = 1
```

This is what I had to do to get it working:

```
$ rm -fr ~/.local/share/nvim/plugged/*
$ vim -u barebones.vim +PlugInstall +q +q
$ go get -u github.com/mdempsky/gocode
```

Next, validate that it's the right `gocode`, it should have a `-source` option:

```
$ gocode -help
Usage: gocode [-s] [-f=<format>] [-in=<path>] [-sock=<type>] [-addr=<addr>]
       <command> [<args>]

Flags:
  -addr string
        address for tcp socket (default "127.0.0.1:37373")
  -debug
        enable server-side debug mode
  -f string
        output format (vim | emacs | nice | csv | csv-with-package | json) (default "nice")
  -in string
        use this file instead of stdin input
  -profile int
        port on which to expose profiling information for pprof; 0 to disable profiling
  -s    run a server instead of a client
  -sock string
        socket type (unix | tcp) (default "unix")

Commands:
  autocomplete [<path>] <offset>     main autocompletion command
  close                              close the gocode daemon
  drop-cache                         drop gocode daemon's cache
  options                            list config options (extended)
  set [<name> [<value>]]             list or set config options
  status                             gocode daemon status report
```

For good measure, `killall gocode` to make sure that nothing is hanging around.

Next, you'll need to patch the `vim-go` source-code at `~/.local/share/nvim/plugged/vim-go/autoload/go/complete.vim`:

```diff
diff --git a/autoload/go/complete.vim b/autoload/go/complete.vim
index 127d57f..279b10c 100644
--- a/autoload/go/complete.vim
+++ b/autoload/go/complete.vim
@@ -9,6 +9,7 @@ function! s:gocodeCommand(cmd, args) abort
   let cmd = [bin_path]
   let cmd = extend(cmd, ['-sock', socket_type])
   let cmd = extend(cmd, ['-f', 'vim'])
+  let cmd = extend(cmd, ['-source'])
   let cmd = extend(cmd, [a:cmd])
   let cmd = extend(cmd, a:args)
 ```

Finally, it completes!

![screenshot from 2018-07-05 12 54 05](https://user-images.githubusercontent.com/347571/42344889-8afce59e-8052-11e8-8302-d1c14e07255f.png)

Special thanks to @Shougo for [patching things within `deoplete-go`!](https://github.com/zchee/deoplete-go/commit/2d402d856d98d4a351fdcf40d837da0cf52ccdfd#diff-04c6e90faac2675aa89e2176d2eec7d8R295) 

I have also [filed an issue with vim-go](https://github.com/fatih/vim-go/issues/1873) to hopefully avoid having to manually patch that file in the future, it should be a boolean or something to choose `mdempsky/gocode` instead of `nsf/gocode` and there should be an option to turn on `-source` (or if on Go >=1.10 it should be a default).
