### ISSUE TITLE
Navigating deoplete list opens scratch buffer

### ISSUE THREAD

**Issue by lpil** [zchee/deoplete-go#131]
Hello! Thanks for this plugin

When I navigate the deoplete list with `<C-n>` or `<C-p>` (or the up/down arrows) it opens a scratch buffer in a split at the top of the window, showing the type signature. This persists after selecting an open.

Is this expected behaviour? How do I disable it?

Thanks,
Louis

**Comment by Shougo** [comment]
`set completeopt-=preview`

**Comment by lpil** [comment]
Thank you so much!
