### ISSUE TITLE
Can't find service Server.AutoComplete

### ISSUE THREAD

**Issue by catvec** [zchee/deoplete-go#133]
Whenever I make any change to a Go source file I get the following error message in NVim:

```
[deoplete] Traceback (most recent call last):
  File "/home/noah/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line
238, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
2018/09/07 00:11:26 rpc: can't find service Server.AutoComplete
.  Use :messages / see above for error details.
```

I'm not quite sure but this might have something to do with the upgrade to Go 1.11 and the original gocode project being deprecated and picked up by go get -u github.com/mdempsky/gocode

**Comment by Shougo** [comment]
I think "gocode close" is needed.

**Comment by Shougo** [comment]
Please read it.
https://github.com/mdempsky/gocode/blob/master/README.md#debugging

**Comment by catvec** [comment]
I think when I upgraded to the other gocode version the old gocode daemon did not close.

`gocode exit` printed an error and `gocode -s -debug` failed to start b/c the socket was already bound.  

Rebooting fixed this issue.

Thank you very much for your help.
