### ISSUE TITLE
Gocode panicked: `[deoplete] NoneType: None`

### ISSUE THREAD

**Issue by karlek** [zchee/deoplete-go#134]
This minimal config panicks everytime a key is pressed when writing in a go file.
```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go',    { 'do': 'make'}
call plug#end()
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#gocode_binary = '$GOPATH/bin/gocode'
```

There is very little information from the panic:
```
[deoplete] NoneType: None
gocode panicked.  Use :messages / see above for error details.
```

```fish
$ go version
go version go1.11 linux/amd64

[~/go/src/github.com/nsf/gocode] $ git rev-parse HEAD
7b1d4e18cdc58a74dc1bd4c2d45b3f1b2ca227c3
```

**Comment by Shougo** [comment]
You should use https://github.com/mdempsky/gocode instead.
nsf/gocode does not support go 1.10+.
Please read README in nsf/gocode.
https://github.com/nsf/gocode

**Comment by karlek** [comment]
Thank you, that was the problem.

_If someone else has this problem, don't forget to kill your old `gocode` daemon with `gocode exit` (or `pkill gocode` if necessary)_

**Comment by cippaciong** [comment]
If anyone using go modules stumbles into this issue and is already using [mdempsky/gocode](https://github.com/mdempsky/gocode), please notice that mdempsky version does not support modules. As suggested in the [README](https://github.com/mdempsky/gocode#githubcommdempskygocode), try using [stamblerre/gocode](https://github.com/stamblerre/gocode).
Remember to stop the daemon with `gocode close`, delete `$GOPATH/bin/gocode` and replace it with the newer version from stamblerre `go get -u github.com/stamblerre/gocode`
