### ISSUE TITLE
external packages has some problem

### ISSUE THREAD

**Issue by glepnir** [zchee/deoplete-go#142]
Hi ，I reinstalled my vim under the new linux computer, my `go version1.11.2`, the latest version of `gocode`, I found that the external package can not be completed, so I set `g:deoplete#sources#go#source_importer`, it works , but very slow, and the standard library can't be completed, but on my mac I'm using `nsf/gocode` and by setting `autobuild true`, it's very fast, I did a test.
On linux
![1](https://user-images.githubusercontent.com/41671631/49774492-e742b900-fd2f-11e8-9468-fd5fdf47d19a.gif)
On Mac
![2](https://user-images.githubusercontent.com/41671631/49774494-e90c7c80-fd2f-11e8-8b0a-726d0acaa13e.gif)

You can see that mdepsky/gocode is very slow on the completion of local external packages.

**Comment by Shougo** [comment]
It is gocode issues instead of deoplete-go.
Please report it in gocode issues.
