### ISSUE TITLE
GoCode completions dont appear until further typing or focus into completions list

### ISSUE THREAD

**Issue by chrispouliot** [zchee/deoplete-go#143]
When attempting to get completions I can only get deoplete-go specific completions if I start typing after the `.` or focus into the completions prompt.

Here is how it looks if I type `.` after a variable

![before](https://dl.dropboxusercontent.com/s/pk8zv5rfh2lvsfl/Screenshot%202019-01-02%2014.58.55.png?dl=0)

Here is how it looks if I focus into the prompt (arrow down) or after I type a character after the `.`

![after](https://dl.dropboxusercontent.com/s/5n4t58hqlr3sdqz/Screenshot%202019-01-02%2014.59.01.png?dl=0)

Before focusing into the prompt there are only a few completions, and the rest appear immediately when I start typing more or when I change focus to the completions list.

Sample init.vim
```
call plug#begin('~/.local/share/nvim/plugged')
" Autocompletion
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': 'make'}
call plug#end()
" Auto completion
let g:deoplete#enable_at_startup = 1


```

NVIM v0.3.2-dev

**Comment by Shougo** [comment]
It is feature.  Because deoplete-go completion is slower than member completion.
You need to wait to get deoplete-go's completion.

Hm...  If you don't like the behavior, you need to disable parallel feature in deoplete.

```vim
       call deoplete#custom#option('num_processes', 1)
```

**Comment by chrispouliot** [comment]
@Shougo It will *never* show up if I just wait after hitting `.`
It will immediately show up when I focus into the prompt or continue typing.
Is this expected?

**Comment by Shougo** [comment]
I don't reproduce your problem with your minimal init.vim.
Please upload the example file to reproduce.

If not, I will ignore your report.
