### ISSUE TITLE
It is slower than visualfc/gocode

### ISSUE THREAD

**Issue by dcy** [zchee/deoplete-go#148]
Hello!
[stamblerre/gocode](https://github.com/stamblerre/gocode) is slower than [visualfc/gocode](https://github.com/visualfc/gocode)

**Comment by Shougo** [comment]
Hm....

OK.  But please provide the information of the difference.

**Comment by Shougo** [comment]
I will add the link.  But I think the default should be `https://github.com/stamblerre/gocode`.
It is more stable.
