### ISSUE TITLE
Neosnippet Snippet's are included in the menu after the dot character

### ISSUE THREAD

**Issue by fatih** [zchee/deoplete-go#15]
Hi,

Even though I've added `ns` to the `ignore_sources` list it still shows after the dot. I thought it shouldn't be the case? I don't want to see the `ns` sources.

![image](https://cloud.githubusercontent.com/assets/438920/12866263/db64af18-ccd0-11e5-8434-4b1e844baf68.png)

My settings are:

```
let g:deoplete#enable_at_startup = 1   "enable deoplete at vim startup
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'member', 'tag', 'file', 'ns']
let deoplete#sources#go#sort_class = ['func', 'type', 'var', 'const']

" Use partial fuzzy matches like YouCompleteMe
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
```

**Comment by zchee** [comment]
@fatih Thanks for using `deoplete-go` :)

`g:deoplete#ignore_sources` value should be source name.
`neosnippet`'s source name is `neosnippet`.
See https://github.com/Shougo/neosnippet.vim/blob/master/rplugin/python3/deoplete/sources/neosnippet.py#L33

Try,

``` vim
let g:deoplete#ignore_sources._ = ['buffer', 'member', 'tag', 'file', 'neosnippet']
```

**Comment by fatih** [comment]
Awesome, thanks for the prompt answer, works great! I've removed YCM from vim-go: https://github.com/fatih/vim-go/commit/e757872d35393544d93ca7640752d53cb714cf35

I'm going to add deoplete.nvim and deoplete-go to the README so people can also start to use ;) Right now I'm trying to make it work but `deoplete.nvim` needs a lot of manual settings.

Thanks for the work :+1:

**Comment by fatih** [comment]
@zchee Also not related, but I think we should not show `ns` after a dot `.`. For example `fmt.` should not show neosnippet. I'm not what to change but I think it's confusing. Maybe because of `rank` ?

**Comment by zchee** [comment]
@fatih :tada: 
and

> I'm going to add deoplete.nvim and deoplete-go to the README so people can also start to use ;) Right now I'm trying to make it work but deoplete.nvim needs a lot of manual settings.

I am also planning to edit more understandable to the `README.md`.
I will implement after a while.

> Also not related, but I think we should not show ns after a dot .. For example fmt. should not show neosnippet. I'm not what to change but I think it's confusing. Maybe because of rank ?

Hmm...
Maybe, caused by there is no `self.input_pattern` in `neosnippet`...?
https://github.com/Shougo/neosnippet.vim/blob/master/rplugin/python3/deoplete/sources/neosnippet.py

/cc @Shougo 

---

FYI, `package` value have not in the `deoplete#sources#go#sort_class`.
Although it is operating, but `package` not complemented.
https://github.com/zchee/deoplete-go/issues/15#issue-131844603

``` vim
let g:deoplete#enable_at_startup = 1   "enable deoplete at vim startup
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'member', 'tag', 'file', 'ns']

" this
let deoplete#sources#go#sort_class = ['func', 'type', 'var', 'const']

" Use partial fuzzy matches like YouCompleteMe
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
```

**Comment by fatih** [comment]
Yeah I don't like package that's why I removed it completely :) Thanks for the input.

**Comment by zchee** [comment]
@fatih Cool :)
and, I fix [README.md#class-sorting](https://github.com/zchee/deoplete-go#class-sorting) later.
It did not have to contain all of the class.

---

BTW, https://twitter.com/fatih/status/688940949641236481

> I even can it do vim-go’s README :)

If you don’t mind, Could you consider again...? :)

**Comment by fatih** [comment]
I'm going to add it to README, sure! But we need to fix the issue where `neosnippet` is included in the source after `.` inside a file with `filetype` set to `go`. So if the user has installed `deoplete.nvim` and `deoplete-go` and is editing a Go file, neosnippet should be not triggered when it comes after a dot. 

This :

```
fmt.
    ^
```

Here we only should show `go` source, not `ns`. This is wrong: 
![image](https://cloud.githubusercontent.com/assets/438920/12866551/2b07dd16-ccda-11e5-80df-211aad79fc59.png)

@Shougo @zchee I hope it is clear?

**Comment by Shougo** [comment]
It is go neosnippet-snippets problem.

@fatih I have improved the printf and println snippets.
And I have removed the built-in functions from neosnippet-snippets
