### ISSUE TITLE
Support for gopls

### ISSUE THREAD

**Issue by svanharmelen** [zchee/deoplete-go#151]
I was wondering if there are any plans to add support for the new gopls Go Language server?

vim-go is already switched to using gopls for completion instead of gocode, and things are much quicker and smoother because of it.

But I like to keep using deoplete for autocompletion, so having support for gopls would be awesome.

Thanks!

**Comment by Shougo** [comment]
Unfortunately, it cannot.
gopls is LSP client.

deoplete-go is not LSP client.
You should use LanguageClient-neovim or deoplete-tabnine instead.

**Comment by svanharmelen** [comment]
Yeah, I was already looking at the language client as well. Will continue down that path then. Thanks!
