### ISSUE TITLE
After completion, braces are not added

### ISSUE THREAD

**Issue by fatih** [zchee/deoplete-go#16]
Right now when I complete:

![image](https://cloud.githubusercontent.com/assets/438920/12866577/2bab90cc-ccdb-11e5-8776-1f48b01a9222.png)

But I want to have:

![image](https://cloud.githubusercontent.com/assets/438920/12866578/31406c1a-ccdb-11e5-88c5-e615bee358e8.png)

How can I achieve it?

**Comment by zchee** [comment]
@fatih It is in accordance with the specifications of gocode, but I use the completion of the last bracket  `)` is https://github.com/Shougo/neopairs.vim .

However, If the user is not using it, I will implemented to the same operation later.
Thanks for the suggestion of the new implementation :)

**Comment by fatih** [comment]
Maybe you can add it to your README.md ? After installing it works fine thanks :)

**Comment by zchee** [comment]
@fatih Yes! I update README.md after use statically json data implementation.

**Comment by fatih** [comment]
Also neopairs doesn't work with neosnippet's feature: https://github.com/Shougo/neosnippet.vim/blob/master/doc/neosnippet.txt#L232

**Comment by Shougo** [comment]
@fatih Yes, because neosnippet has same feature.
It conflicts with neopairs behavior.

**Comment by nhooyr** [comment]
We should close this.

@fatih add this to your vimrc 

```vim
call deoplete#custom#set('_', 'converters', ['converter_remove_paren'])
```

**Comment by zchee** [comment]
@fatih @Shougo The original problem of this issue is already implemented by the `neopairs.vim`.
Close.

**Comment by svanharmelen** [comment]
@zchee did anything change lately? I used to have an opening brace on completions like this: 
![2bab90cc-ccdb-11e5-8776-1f48b01a9222](https://cloud.githubusercontent.com/assets/4171547/13965142/70d7d380-f06d-11e5-99a5-fa9771ebc08f.png)

But now I notice I don't have the opening brace anymore and just have: `fmt.Println`. Any way I can get the old behaviour back? I do not use `neopairs.vim` as I don't care about the closing brace, just the opening brace...

**Comment by zchee** [comment]
@svanharmelen Do you want automatically insert close bracket without neopairs?
Or `(`?

**Comment by svanharmelen** [comment]
@zchee no, I want to automatically get the opening bracket...

**Comment by zchee** [comment]
@svanharmelen OK :)
Try https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L503

https://github.com/zchee/deoplete-go/commit/82977f0e7150973050d07bfedf46d5a7c5f0ef7a.

**Comment by svanharmelen** [comment]
Ah, check!

Adding `call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])` works perfect. Thanks!!

**Comment by zchee** [comment]
@svanharmelen :tada: 
I'll add information to README :)

**Comment by svanharmelen** [comment]
Great! Thanks again for the quick help @zchee!

**Comment by zchee** [comment]
@svanharmelen NP🎵
