### ISSUE TITLE
deoplete gocode binary not found error

### ISSUE THREAD

**Issue by JC1738** [zchee/deoplete-go#164]
I recently started getting this error.  Below is my configuration.  I am not sure what has changed.  (nvim, ubuntu 20.04)

https://github.com/JC1738/dotfiles/blob/b7eddc8335cf96c360d444d33342e5a1b4ccaaf6/config/nvim/init_linux.vim#L667

There was one suggestion on another issue for vim-go to try:  `AutocmdFT go call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })` but that didn't help.

`
"----------------------------------------------
" Plugin: zchee/deoplete-go
"----------------------------------------------
" Enable completing of go pointers
AutocmdFT go call deoplete#custom#source('go', 'matchers', ['matcher_full_fuzzy'])
AutocmdFT go call deoplete#custom#source('go', 'sorters', [])
AutocmdFT go let g:deoplete#sources#go#align_class = 1
AutocmdFT go let g:deoplete#sources#go#cgo = 1
AutocmdFT go let g:deoplete#sources#go#cgo#libclang_path= expand("/usr/lib/llvm-10/lib/libclang.so")
AutocmdFT go let g:deoplete#sources#go#cgo#sort_algo = 'alphabetical'
AutocmdFT go let g:deoplete#sources#go#gocode_binary = globpath($GOPATH,"/bin/gocode")
AutocmdFT go let g:deoplete#sources#go#json_directory = globpath($NVIM_HOME,"/plugged/deoplete-go/data/json/*/").expand("$GOOS")."_".expand("$GOARCH")
AutocmdFT go let g:deoplete#sources#go#package_dot = 1
AutocmdFT go let g:deoplete#sources#go#on_event = 1
AutocmdFT go let g:deoplete#sources#go#pointer = 1
AutocmdFT go let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
AutocmdFT go let g:deoplete#sources#go#use_cache = 1
AutocmdFT go call deoplete#custom#option('omni_patterns', { 'go': '[^. *\t]\.\w*' })
`

**Comment by JC1738** [comment]
Thanks, I solved my problem.  I wiped my go directory and never re-installed gocode itself.  Lots of debugging for a simple error.

**Comment by Shougo** [comment]
OH
