### ISSUE TITLE
Not enough space between constant and identifier

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#20]
Due to line 75 in go.py

``` python
abbr = '{:<5}'.format(_class) + complete['name']
```

I get the following problem.

<img width="1440" alt="screen shot 2016-02-06 at 10 27 14 pm" src="https://cloud.githubusercontent.com/assets/10180857/12870743/c8487964-cd20-11e5-903c-a149eb489bc9.png">

No space between `const` and the identifiers in the completion popup.
I think we should instead do something like

``` python
abbr = _class + ' ' + complete['name'] + ' ' + complete['type']
```

**Comment by zchee** [comment]
@nhooyr Thanks!
You are right. I will fix later.

but, If does not format of `_class`, it will be column does not align.

![screenshot 2016-02-07 12 32 12](https://cloud.githubusercontent.com/assets/6366270/12870759/e3743414-cd96-11e5-8ab9-7801308e6d60.png)

so I think `6` istead of `5`.

``` python
abbr = '{:<6}'.format(_class) + complete['name']
```

**Comment by nhooyr** [comment]
I dunno. I don't think its necessary to align them. Looks fine to me. Do you think maybe we should have an option. Making it 6 just adds a really weird gap.

**Comment by fatih** [comment]
I think we should align them. Makes reading it much more easier and there is alignment too for `gocode`.

**Comment by zchee** [comment]
@fatih I discuss to @nhooyr on https://github.com/zchee/deoplete-go/pull/22.
yea, I will create on/off options for automatically dot`.`, alignment, or etc...

**Comment by fatih** [comment]
Alright, seems like alignment shouldn't be done because the number of items will be decreased with every key you type, this could be problematic when there is a very long variable name with a very short. So I'm not in favor of alignment anymore, fyi.
