### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#25]
I think we should include a license.

**Comment by zchee** [comment]
@nhooyr License...
I do not have include License:( I do not understand it well.

Shougo use `MIT license`, Golang use `BSD license`.
What would be good?

**Comment by nhooyr** [comment]
lets see what @Shougo thinks.

**Comment by Shougo** [comment]
I like `MIT license`...
But you can decide it.

**Comment by zchee** [comment]
@nhooyr I planned to select the MIT accordance with @Shougo.
WDYT?

**Comment by nhooyr** [comment]
@zchee perfectly fine. go ahead

**Comment by zchee** [comment]
Added.
@Shougo Thanks advice.

Close.

**Comment by nhooyr** [comment]
@zchee don't make the license a markdown file. have no extensions. E.g. just `LICENSE`

**Comment by zchee** [comment]
@nhooyr Ah, I missed.
fix now.
