### ISSUE TITLE
Reddit post

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#26]
This plugin is already better than any go completion plugin out there. Can I post it on reddit and such to get people using it?

**Comment by zchee** [comment]
@nhooyr Of course!!
I not good at English, so I can't post on reddit.
If you post on my behalf, it is very grateful for me :)

**Comment by nhooyr** [comment]
@zchee update the description, we don't use vim-go anymore.

**Comment by nhooyr** [comment]
1. https://www.reddit.com/r/neovim/comments/44oza7/fully_asynchronous_autocompletion_deoplete_source/?ref=share&ref_source=link
2. https://www.reddit.com/r/golang/comments/44oupo/fully_asynchronous_autocompletion_deoplete_source/?ref=share&ref_source=link
