### ISSUE TITLE
Remove the last section of the README

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#27]
You know the part about
## Why do `deoplete` and `deoplete-go` not use `omnifunc`?

I think we should just remove this, I only posted about it in the other issue because I was very confused. I don't think its necessary anymore. Its a given that omnifunc would block the user interface, thats the whole point of deoplete. Thats something users should read about in the deoplete documentation, not the plugin.

**Comment by zchee** [comment]
@nhooyr yea.
Previously, it was put because any users do not understand the deoplete.
I remove it later.

**Comment by nhooyr** [comment]
I gotcha, I noticed a few mistakes in the readme again. It should be final though now. Can I create a PR with that section removed and my fixes? Sorry about all the PRs. Every time I submit one, I notice a new mistake lol.

**Comment by zchee** [comment]
@nhooyr Off course.
I hope that it is fixed in your English.
