### ISSUE TITLE
No completion after typing a dot...

### ISSUE THREAD

**Issue by svanharmelen** [zchee/deoplete-go#30]
See this small screencast:

![feb 08 2016 15 12](https://cloud.githubusercontent.com/assets/4171547/12888719/aa26a292-ce7b-11e5-9d3f-5ec6663c8f42.gif)

I would expect that after typing the dot, it should suggest completions. But it doesn't do that till after typing the second character after the dot.

**Comment by zchee** [comment]
@svanharmelen Hi :)

I try to debug this, Could you post `init.vim` and this go file?

**Comment by svanharmelen** [comment]
@zchee when trying to create a minimal `init.vim` I failed to reproduce the issue. Tried my normal `init.vim` again and it now works as expected (without any changes). Strange... But all seems to working as expected :grin:

**Comment by svanharmelen** [comment]
Uuh... I just had it again. You should be able to reproduce this very easily by copying the code below:

``` go
package main

import "net"

func main() {
  n1 := &net.IPNet{}
  n1.
}
```

It turns out that this problem is related to the name of the variable. As you can see, the variable name ends with a number (the digit 1), which seems to cause this.

So maybe this is due to the regex used to match the pattern? Looking at that one...

**Comment by svanharmelen** [comment]
Yep... It's the regex: `'[^. \t0-9]\.\w*'`

I'll make a PR with a fix in a moment.

**Comment by svanharmelen** [comment]
Fixed by PR #31

**Comment by Shougo** [comment]
Thanks!

I don't know the go language specification.
Go language cannot call the functions like them?

```
'string'.foo()
['hoge'].object()
```

**Comment by nhooyr** [comment]
@Shougo can't call either.

**Comment by mmlb** [comment]
@nhooyr you are correct about the former, but not latter: https://play.golang.org/p/zwEMuC1ulm

**Comment by nhooyr** [comment]
@mmlb `['hoge']` is different from `m["1"]`

**Comment by svanharmelen** [comment]
Oeps! The regex is for matching all valid identifiers (for packages, types and variables), but indeed I totally forgot about using the dot to invoke something on the return value of a func or index operation.

Have a meeting first, but will update the regex after that. The update in PR #34 fixes one use case, but it's not complete...

**Comment by nhooyr** [comment]
@svanharmelen definitely.

**Comment by mmlb** [comment]
@nhooyr indeed, was mostly making a mis-worded statement on having to handle index returns.
