### ISSUE TITLE
Add import completion

### ISSUE THREAD

**Issue by dobegor** [zchee/deoplete-go#32]
I wish there was import completion like in LiteIDE.
I.e. you typed:

```
import "fm
```

and it offers `fmt` package to import.

**Comment by nhooyr** [comment]
This is more of an issue with gocode. Also vim-go has the `:GoImport` command which offers autocomplete.

**Comment by dobegor** [comment]
@nhooyr 
LiteIDE has this feature without gocode, so I guess one can look at the implementation in it.
:GoImport isn't really useful when you don't know the head part of package's path.

**Comment by nhooyr** [comment]
@dobegor https://github.com/nsf/gocode/issues/257

It would make much more sense to let gocode handle it than do it ourselves.

**Comment by nhooyr** [comment]
@dobegor what do you mean it isn't useful? it works perfectly fine for me.

**Comment by zchee** [comment]
@dobegor @nhooyr Hi,
I was also planned. but we have `goimports`, so was thinking whether we need.

However, see https://github.com/zchee/deoplete-go/pull/19
If has been merged, the name of the Go stdlib can be retrieved.
and https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/jedi.py#L41-L44

It is possible to display the package name if current input is `import`.

I think maybe performance reduced, but will not significantly affect because statically cache.

WDYT?

**Comment by zchee** [comment]
@dobegor @nhooyr or, If current input is `import`, call it.
https://gist.github.com/zchee/bdfe8b1967d3f958caee

It 's `fmt`, `os`, `net`, `strconv`, `syscatll` listed.

# 

sorry.
I woke up earlier, so English is rough

**Comment by zchee** [comment]
@dobegor @nhooyr 
I will explain in detail later...

**Comment by dobegor** [comment]
@zchee looks great, good morning then :)
waiting for details on that feature.

**Comment by zchee** [comment]
@dobegor At first, I wrote the details of the flow.
Check it.
https://github.com/zchee/deoplete-go/pull/19#issue-131914074

**Comment by zchee** [comment]
@dobegor At second, sloppy but...

``` python
    def gather_candidates(self, context):
        buf = self.vim.current.buffer
        pkgs = self.GetCurrentImportPackages(buf)
        parent = str(context['input']).strip('\t')
        pkg_data = os.path.join(self.data_directory, parent + 'json')

        if parent not in pkgs and '.' in parent and os.path.isfile(pkg_data):
            with open(pkg_data) as json_pkg_data:
                result = loads(json_pkg_data.read())

        elif re.match(r'^\s*import \w*', parent):
            # packages.json is https://gist.github.com/zchee/bdfe8b1967d3f958caee
            with open(os.path.join(self.data_directory,
                                   'packages.json')) as json_pkg_data:
                result = loads(json_pkg_data.read())

        else:
            line = self.vim.current.window.cursor[0]
            column = context['complete_position']

            offset = self.vim.call('line2byte', line) + \
                charpos2bytepos(self.vim, context['input'][: column],
                                column) - 1
            source = '\n'.join(buf).encode()

            .
            .
            .
```

Currently, conditions only `parent` is `import`. 
If the newly created `re.match()`, performance is reduced.
so I'm going to fix the `self.GetCurrentImportPackages(buf)` method.
e.g. (arg name is rough)

``` python
self.GetCurrentImportPackages(buf, resultIsPackageNameOrJsonData?)
```

**Comment by zchee** [comment]
@dobegor May I ask if you understand what I mean?

@nhooyr We can be acquired without execute a `gocode`, It is whether to adopt this.

**Comment by nhooyr** [comment]
@zchee i really think we shouldn't bother, much rather let gocode. Its not really a urgent feature, goimports works perfectly fine. Its autocomplete is nice. If you really want to, go ahead, there is no real harm. It might add some needless complexity though.

**Comment by zchee** [comment]
@nhooyr Yes.
It's possible. but it is also complicated.
I think it is the work of `goimports`. so I do not like the implements of this.

@dobegor WDYT?

**Comment by dobegor** [comment]
@zchee so this will only allow to auto-complete a fixed set of import paths?
I guess we need to make a way to generate package.json for all packages in $GOPATH, for example, (imports-cache) command. It will parse $GOPATH and generate import paths for each package, then autocompletion will perform fast fuzzy matching along this list.

I have literally 2 days experience with Vim, but I can certainly write such utility in Golang (using third-party lib for fast fuzzy matching).

**Comment by nhooyr** [comment]
@dobegor why don't you just modify `gocode` to do this. That way every single editor that uses `gocode` will be able to take advantage of that functionality without changing anything.

**Comment by zchee** [comment]
@dobegor 

> I guess we need to make a way to generate package.json for all packages in $GOPATH, for example, (imports-cache) command. It will parse $GOPATH and generate import paths for each package, then autocompletion will perform fast fuzzy matching along this list.
> I have literally 2 days experience with Vim, but I can certainly write such utility in Golang (using third-party lib for fast fuzzy matching).

Now, `gocode` are looking for collaborators https://github.com/nsf/gocode/issues/307.

If you said implements are realized, and faster than `gocode`, We will consider adoption it.
but at present, bad idea not to use the `gocode`.

---

I'm sorry if my understanding is wrong.

**Comment by nhooyr** [comment]
@zchee I'm gonna take a stab at implementing it in gocode. I'll update once I have it done.

**Comment by zchee** [comment]
@nhooyr I looking forward update.

**Comment by nhooyr** [comment]
@zchee nsf/gocode#332

**Comment by zchee** [comment]
@nhooyr Thanks!
I'll check that PR later.

**Comment by nhooyr** [comment]
Once its merged (likely tomorrow) we just need to update our regex for completion in strings, as well as add a new class import. Thats it.

**Comment by zchee** [comment]
@nhooyr I got it.

**Comment by nhooyr** [comment]
Its been merged!

**Comment by zchee** [comment]
@nhooyr Yeah!!!!
I'll update and test :)

> we just need to update our regex for completion in strings, as well as add a new class import.

I would like to confirm, but it meaning is `input_pattern`?

**Comment by nhooyr** [comment]
yes.

**Comment by zchee** [comment]
@nhooyr OK.

I will update the input pattern corresponding to it. (Maybe tomorrow...)

**Comment by zchee** [comment]
@nhooyr I test `import` completion feature.
Not required modifying `input_pattern`. It worked perfectly :)

I small fixed for when `align_class` is enabled.
- https://github.com/zchee/deoplete-go/commit/45d5c7ba70854ce6ec1a4e77baa1c8df75504b29

@dobegor This feature has been the implementation.
Close :)

**Comment by nhooyr** [comment]
@zchee https://asciinema.org/a/3xz29k70w2zmi27sg2zugde74

just a slight problem.

**Comment by zchee** [comment]
@nhooyr Oh, Good catch. Thanks.

Actually, it seemed necessary fixes for `self.input_pattern` :(
(It is very difficult to understand `(?:\b[^\W\d]\w*|[\]\)])\.(?:[^\W\d]\w*)?` regex... :scream:)

**Comment by nhooyr** [comment]
haha. take a look at the previous PRs, its explained there
https://github.com/zchee/deoplete-go/pull/35
https://github.com/zchee/deoplete-go/pull/36

**Comment by zchee** [comment]
@nhooyr Yea.
When to implementing this feature, because I thought it was necessary to change the input_pattern, I had to try it. About 30 minutes...
However, was not able to completely understand :joy:

I will try again from now... (I do not know how long it takes. lol)

# 

FYI, I separated this problem https://github.com/zchee/deoplete-go/issues/46

**Comment by zchee** [comment]
@nhooyr 
Off topic: Could you tell me your twitter ID?
My TW: https://twitter.com/_zchee_

**Comment by nhooyr** [comment]
@zchee its the same, `nhooyr`. I'll change it if you want, I think I know whats wrong.
