### ISSUE TITLE
Cached completion problem?

### ISSUE THREAD

**Issue by dobegor** [zchee/deoplete-go#33]
I once exported a function from a package, now everytime I import this package and type "package_name." it shows me it has this function, but it doesn't (I removed it).

Also it doesn't show me a structure exported from it until I type it manually.
Latest stable Neovim version, deoplete and deoplete-go, with vim-go.

On the screenshot: there is no such function in that package and User and UserService structs can't be found (I assume that [M] means it was manual-completed)

![pb_sucks2](https://cloud.githubusercontent.com/assets/14029650/12903245/ec559d46-cece-11e5-95ef-c01f0e3cab4d.png)

**Comment by svanharmelen** [comment]
No, [M] means it comes from the 'member' source (see the deoplete docs for more info.

Also gocode makes completion suggestions based on compiled libs and packages. So if your program is changed but not recompiled, it could be serving completions based on outdated code.

So do a (full) build and check again. If still no success try to clear your gocode cache and/or set gocode to autobuild (gocode set autobuild true). That last one can slow things down from time to time as it will compile stuff more often (which you'll notice when working on bigger Go packages/programs).

In every case l don't think this is deoplete-go but the gocode daemon...

**Comment by dobegor** [comment]
@svanharmelen 
I've done:

```
gocode drop-cache
gocode set autobuild true
```

but the result remains absolutely the same.
I am using vim-go, too, if it's important.

I've even tried killing gocode daemon before restarting NVim with same result. 

My init.vim: [gist](https://gist.github.com/dobegor/60875d1000fc6950829f)

**Comment by dobegor** [comment]
@svanharmelen 
I deleted a .a file in $GOPATH/pkg and it works ok now.
But I tried rebuilding that package with vim-go (:GoBuild) and it built successfully, but the issue remained.

What I am supposed to do everytime I change package's exports? I don't want to clean .a file for that package everytime.

**Comment by dobegor** [comment]
Well, I think it's certainly a gocode issue.
autobuild option just doesn't work for me.
But is there any way to workaround it?

**Comment by nhooyr** [comment]
@dobegor you need to build the library again for gocode to update. It parses the binaries.

**Comment by dobegor** [comment]
@nhooyr thanks, it worked for me with go install (:GoInstall, or call (go-install) ).
but that's really annoying - I need to do it on every package separetly when I want to update autocompletion. any suggests about that?

I know my questions could be bit annoying since I am new to Vim/Neovim, but this part isn't really document in gocode/vim-go/deoplete. Thanks.

**Comment by nhooyr** [comment]
No real solutions, its a problem with gocode.

https://github.com/nsf/gocode/issues/307

**Comment by dobegor** [comment]
@nhooyr oh, ok, it's clear for me now, thanks!
I think I need to close it, as it can't be fixed by deoplete-go/deoplete.

**Comment by dobegor** [comment]
@nhooyr 
I am sorry, this has nothing to do with this issue, but I haven't found docs for some deoplete/deoplete-go settings. Maybe I am wrong, so it would be stupid to create an issue about that, and there is no IRC channel to ask such things.
How do I disable Scratch/Preview window? 

![pb_sucks2](https://cloud.githubusercontent.com/assets/14029650/12924033/d1336a4c-cf60-11e5-9bb6-6ad6dc2ae688.png)

**Comment by nhooyr** [comment]
@dobegor read more docs

``` vim
set completeopt-=preview
```

Deoplete still uses vim's menus and autocomplete for completing, read up on how vim's autocomplete works. This is all over google too.

**Comment by dobegor** [comment]
@nhooyr sorry, I didn't know vim has it's own menus for this. Thanks. I will stop asking here :smile:

**Comment by zchee** [comment]
@nhooyr @svanharmelen Thanks for assistance!!
