### ISSUE TITLE
Do not use omni source in go files

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#4]
I'd say we should add this to the example configuration so that deoplete doesn't use the omnifunc. It results in weird behaviour for me like the completions being inserted and then quickly deleted and it doesn't properly respect auto_completion_start_length (if you try fmt. it will show everything inside of fmt which may not be what you want it to do, whereas the plugin respects the length). In fact there is no point to this plugin with the omni source enabled. Instead add this to the example config file.

```
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources.go = ['omni']
```

This disables the omni source in go files. It is a much more smooth experience for me after this change as after adding a period to the package identifier (more detail description below) a giant list doesn't pop up.

**Comment by nhooyr** [comment]
Turns out the appearing and disappearing of the first item in the list happens with the plugin as well if the start_length is 0. 

So if I type

```
fmt.
```

It shows me the entire list of completions but it types in Errorf( and then quickly deletes it. Because the plugin respects the start length you can change it to 1 to fix this but you can't with the omnifunc.

**Comment by nhooyr** [comment]
We should add this for now but I'll submit a deoplete issue.

**Comment by Shougo** [comment]
It conclicts the omni source.
I can remove the pattern in omni source.
But I think the completion plugin is not stable.

@zchee Ping.

**Comment by Shougo** [comment]
> It results in weird behaviour for me like the completions being inserted and then quickly deleted and it doesn't properly respect auto_completion_start_length (if you try fmt. it will show everything inside of fmt which may not be what you want it to do, whereas the plugin respects the length).

It is the feature.
You should change the go source's min_pattern_length like this.

``` vim
        call deoplete#custom#set('go',
        \ 'min_pattern_length', 2)
```

**Comment by Shougo** [comment]
> Turns out the appearing and disappearing of the first item in the list happens with the plugin as well if the start_length is 0. 

It is neovim/Vim feature.  And it should be fixed Yes.
https://github.com/Shougo/neocomplete.vim/issues/464

**Comment by nhooyr** [comment]
@Shougo thanks for explaining it. hope it gets fixed soon.

**Comment by nhooyr** [comment]
@Shougo 

Adding

``` vim
call deoplete#custom#set('go',
\ 'min_pattern_length', 2)
```

Will not fix it because that changes it for the go source. I already have it set to 2. The problem is when its set to 0 or the omni source is being used. The reason is that right after I type a period after the package identifier (for example 'fmt') what happens is that it shows me the entire list of identifiers in the package. This causes weird flashing for some reason and a giant long list which defeats the purpose of setting the start_length. But if you use the plugin with the start_length set > 0 then it waits till you type that many characters after the period before showing you all the identifiers.

**Comment by Shougo** [comment]
Hm.  It is intended behavior.
I will fix the flash though.

**Comment by nhooyr** [comment]
@zchee well as shougo pointed out the 'deoplete#custom#set' there is no need for this plugin for now as the omni source does the exact same thing. I didn't realize you can call that function on it.

This setup works really well for me without the plugin.

``` vim
augroup deoplete 
    autocmd!
    au VimEnter * call deoplete#custom#set('member', 'min_pattern_length', 1)
    au VimEnter * call deoplete#custom#set('omni', 'min_pattern_length', 1)
augroup END
```

The member min_pattern_length has to be set to 1 or you get weird problems where you have to backspace to show all completions. I opened an issue Shougo/deoplete.nvim#131 but it got closed and I don't know why lol.

**Comment by zchee** [comment]
@nhooyr Thanks issue.
I discuss to @Shougo this issue now.
and, I do not understand all.

Please wait a litte... :(

**Comment by zchee** [comment]
@nhooyr Sorry, It is in discussion now, but it is difficult to grasp the bad resolution of the video.

**Comment by zchee** [comment]
@nhooyr Sorry, It is in discussion now, but it is difficult to grasp of your neovim operation the bad resolution of the video.
https://github.com/Shougo/deoplete.nvim/issues/131#issue-127078384
https://www.youtube.com/watch?v=2f_lpskwVgQ&feature=youtu.be

Could you re-recording use asciinema?

https://asciinema.org/
https://github.com/asciinema/asciinema

How to recording use asciinema
1. Install asciinema
   - https://asciinema.org/docs/installation
2. Start recording
   - Type `asciinema rec` and `Enter`.  and re `Enter`
3. To the operation, you want to record.
4. Back to a terminal. and type `exit` then recording will end.
5. Type `Enter`. After a little, url of the video will be displayed.
6. Please post that url on this issue.

Example.
https://asciinema.org/a/31855
https://asciinema.org/a/30892

**Comment by zchee** [comment]
@nhooyr Also, Screenshot.

![screenshot 2016-01-18 03 40 15](https://cloud.githubusercontent.com/assets/6366270/12379160/8f70a2da-bd97-11e5-92ee-a9f604804ad6.png)

![screenshot 2016-01-18 03 56 24](https://cloud.githubusercontent.com/assets/6366270/12379161/9d3d3b26-bd97-11e5-8fa7-a49e52695b5f.png)

**Comment by nhooyr** [comment]
Alright Ignore everything I've said before. I'm gonna explain it again but with the asciinema and in a new issue. I have to leave right now but I'll be back very soon.

**Comment by zchee** [comment]
@nhooyr OK, Thanks.

I look foward to new issue.

**Comment by Shougo** [comment]
@nhooyr I have removed the default omni pattern from omni source.

**Comment by nhooyr** [comment]
@Shougo that means I have to install this plugin for go to be a autocompleted right? omni is still working fine for me. Until this plugin offers something that the omni completion doesn't I think you should just keep the omni. There is no real need to install this plugin yet.

**Comment by Shougo** [comment]
> @Shougo that means I have to install this plugin for go to be a autocompleted right? omni is still working fine for me. 

You can enable the omni source by `g:deoplete#omni#patterns`.
But I recommend for you to use deoplete-go.
It is better choice.

**Comment by zchee** [comment]
@nhooyr Yes, `deoplete-go` implementation is different from the omnifucn that `gocode` provided.

but, when deoplete call `omnifunc`, will block user interface a little bit.
So, If `gocode` returned big dictionary omnifunc completion list, your neovim will slightly freeze.

However, if use the `deoplete` source file, `deoplete` can get a dictionary completion word list asynchronously.
The advantage of `doeplete` also `deoplete-go` is it.
`omnifunc` too slow compared with the deoplete source.

So, If `deoplete-go` return values are exactly the same as `omnifunc`, we not necessary `omnifunc`.
This is the meaning @Shougo has deleted code.

**Comment by nhooyr** [comment]
Alright thank you very much everyone!

**Comment by zchee** [comment]
@nhooyr :tada:
