### ISSUE TITLE
Trouble getting this to work on arch linux

### ISSUE THREAD

**Issue by hhenkel** [zchee/deoplete-go#41]
Hi,

I'm running arch linux and installed NVIM 0.1.2 and it seems like base deoplete works for me, as I get suggestions for words that are already in the file. For go files I don't get any suggestions.

My init.vim:

```
call plug#begin('~/.config/nvim/plugged')
" Colorscheme for vim
Plug 'morhetz/gruvbox'
Plug 'altercation/vim-colors-solarized'
" Nice statusline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Create tmux status line that fits the airline 
Plug 'edkolev/tmuxline.vim'

" Go devel plugins
Plug 'fatih/vim-go'
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-go', { 'do': 'make'}
Plug 'nsf/gocode', { 'rtp': 'nvim', 'do': '~/.config/nvim/plugged/gocode/nvim/symlink.sh' }
call plug#end()

set background=dark
colorscheme gruvbox
"colorscheme solarized

set number
syntax on
filetype on
filetype plugin on
filetype indent on

set autoindent
set modeline
set cursorline
set cursorcolumn

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

let g:airline_powerline_fonts=1
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#align_class = 1
```

neovim-python package is installed and 

```
:echo has('python3')
```

returns 1.

It is rather intersting that even that there is the file "~/.config/nvim/.init.vim-rplugin~" :

```
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/xtc/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete.py', [
      \ {'sync': 1, 'name': 'DeopleteInitializePython', 'type': 'command', 'opts': {}},
     \ ])


" python plugins
```

I can run 

```
:UpdateRemotePlugins
```

in a new terminal window and get

```
remote/host: python3 host registered plugins ['deoplete.py']
```

I tried to run nvim in debug log level, but did not find obvious errors in the log file. I also tried running gocode in debug mode in foreground via

```
gocode -s -debug
```

I did not see any messages from gocode when I tried to write within a go file.

**Comment by zchee** [comment]
@hhenkel Hi :)
Hmm...I think no problem your `init.vim`.

but, `deoplete-go` is not required `gocode` in runtimepath. need `gocode` binary only.
Could you try remove this?

``` vim
Plug 'nsf/gocode', { 'rtp': 'nvim', 'do': '~/.config/nvim/plugged/gocode/nvim/symlink.sh' }
```

**Comment by zchee** [comment]
@hhenkel and, Why re-added `deoplete.nvim` in `runtimepath`?
Already it has been introducing.

``` vim
" Go devel plugins
Plug 'fatih/vim-go'
" this line
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-go', { 'do': 'make'}
.
.
.
" not need set
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
```

**Comment by hhenkel** [comment]
Hi @zchee ,
I removed the runtimepath and nsf/gocode plugin. I then deleted all the plugins and reinstalled them. No luck so far...I tried with the following code in a file called "main.go":

```
package main

import "fmt"

func main() {
        fmt.Println("TEST")
        fmt.Println("TEST2")
        fmt.Println("Test3")
}
```

Please find attached the debug log.

[log_8494.txt](https://github.com/zchee/deoplete-go/files/129621/log_8494.txt)

**Comment by zchee** [comment]
@hhenkel Hmm...

I have prepared more tiny `init.vim`.
It has been edited for your `$HOME` environment. I tested. works successfully.
Could you try it? and please repost debug logs.

``` bash
nvim -u xtc.vim main.go
```

``` vim
:UpdateRemotePlugins
```

again

``` bash
nvim -u xtc.vim main.go
```

https://gist.github.com/zchee/e3d2461f56f903a6b652

**Comment by hhenkel** [comment]
I tried your config, but to me it still seems like it is not working:
![neovim](https://cloud.githubusercontent.com/assets/2813782/13033513/8e294a84-d319-11e5-8aba-dacbd722d286.png)

**Comment by hhenkel** [comment]
Okay, I'm now able to see some output from gocode:

```
2016/02/14 12:58:40 -------------------------------------------------------
2016/02/14 12:58:40 Import path "fmt" was not resolved
2016/02/14 12:58:40 Gocode's build context is:
2016/02/14 12:58:40  GOROOT: /usr
2016/02/14 12:58:40  GOPATH: /home/xtc/go
2016/02/14 12:58:40  GOOS: linux
2016/02/14 12:58:40  GOARCH: amd64
2016/02/14 12:58:40  GBProjectRoot: ""
2016/02/14 12:58:40  lib-path: ""
2016/02/14 12:58:40 Error parsing input file (inner block):
2016/02/14 12:58:40  7:6: expected selector or type assertion, found ';'
2016/02/14 12:58:40 extracted expression tokens: fmt
2016/02/14 12:58:40 Offset: 0
2016/02/14 12:58:40 Number of candidates found: 0
2016/02/14 12:58:40 Candidates are:
2016/02/14 12:58:40 =======================================================
```

**Comment by zchee** [comment]
@hhenkel `GOROOT=/usr` and `GOPATH=/home/xtc/go` is correct?
and, maybe `deoplete-go` can not find `gocode` binary.

Try

``` bash
which gocode
```

and, use that result,

``` vim
let g:deoplete#sources#go#gocode_binary = '/path/to/gocode'
```

**Edit:** Oh, it seem `gocde` worked.
Hmm...

**Comment by hhenkel** [comment]
@zchee it seems like `GOROOT` was not completely correct, I altered to `/usr/lib/go`.

For installing Go on Arch Linux I followed https://wiki.archlinux.org/index.php/Go and chose to install `gcc-go`. Maybe this is the issue, as I only find stuff like this?

```
$ ll /usr/lib/go/5.3.0/x86_64-unknown-linux-gnu/fmt.gox 
-rw-r--r-- 1 root root 3776 Dec 16 11:25 /usr/lib/go/5.3.0/x86_64-unknown-linux-gnu/fmt.gox
```

I don't think there is an issue with finding gocode, it more looks like gocode can't find the correct files.

**Comment by hhenkel** [comment]
I installed `go` and `go-tools` which removed `gcc-go`. The directory structure is more likely to be correct now:

```
$ tree -L 1 /usr/lib/go
/usr/lib/go
├── bin -> /usr/bin
├── doc -> /usr/share/go/doc
├── favicon.ico
├── lib
├── pkg
├── site
├── src
└── VERSION

6 directories, 2 files
```

**Comment by zchee** [comment]
@hhenkel I use OS X, so I do not Arch Linux, `gccgo` and pacman(yaourt?) environment :(
but it seem  `gocode` wrong `$GOROOT`, There is worth a try.

``` vim
" In init.vim
let $GOROOT = '/usr/lib/go'

" and in nvim console
:echo $GOROOT
```

**Comment by zchee** [comment]
@hhenkel  and, For gocode to determine whether the cause, try this commands.

``` bash
gocode -in main.go autocomplete 86
```

**Comment by hhenkel** [comment]
@zchee thanks for your help, I was able to resolve the issue. It seems like something was borked with the gocode binary that came out of my home. I deleted it and installed https://aur.archlinux.org/packages/gocode-git which resolved my problems:

![neovim1](https://cloud.githubusercontent.com/assets/2813782/13033884/2258185a-d326-11e5-9c82-3fa86ee37242.png)

**Comment by zchee** [comment]
@hhenkel Yeah :tada: 

---

BTW, FYI not recommend `completeopt+=preview`.
See also https://github.com/zchee/deoplete-go/issues/40#issuecomment-183630514
