### ISSUE TITLE
Does not close gocode when nvim closes

### ISSUE THREAD

**Issue by coolbry95** [zchee/deoplete-go#43]
It currently does not close gocode when nvim closes. If you open a go file then exit nvim the gocode process does not close. I do not know how to add it into this plugin because should deoplete include a method in the base class for on nvim close called `Shutdown()` or should it be handled within each plugin? Adding it into deoplete will have the advantage of making it easier to make plugins in the long run sense deoplete will only control the shutdown needs to occur. Other source plugins may rely on external servers.

If it is the first case and maybe for the latter case one could make the variable`self.process` and then open the process as is now and maybe adding `autocmd VimLeave * call s:functiontocallShutdown()`. The `functiontocallShutdown` just calls`py3 deoplete-go.Shutdown()`. 

Closing gocode is as simple as `process.stdin.write('close')`. 

The process should most likely be closed on nvim exit because there could be other buffers within nvim  that are go files.

I am not an expert and have never written a vim plugin before. I have just looked at the source code for deoplete-go and deoplete.

**Comment by nhooyr** [comment]
Why do you need it to close? There is no harm in leaving it running.

**Comment by coolbry95** [comment]
There is not point to leaving it open. Once I close neovim there is no need to have gocode running anymore because nothing else is using it.

**Comment by zchee** [comment]
@coolbry95 Certainly, It is useless if you do not start any more nvim.

But If you kill to gocode, it takes a binary start-up cost if the next time you start the nvim.
Do not need that cost is a feature of the gocode, also is why gocode is a daemon.

We should not interfere with its amazing features.

**Comment by nhooyr** [comment]
It takes very little resources when idle, but @coolbry95 if you really feel you need it closed, add this to your `init.vim`

``` vim
augroup gocode
  autocmd!
  autocmd VimLeave * call system('gocode close')
augroup END
```

**Comment by coolbry95** [comment]
I understand the startup costs. The solution @nhooyr provides is good enough.

**Comment by zchee** [comment]
@coolbry95 Thanks :)

@nhooyr Thanks for additional advice!
