### ISSUE TITLE
faster regex?

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#44]
The current regex is really slow for me, and I mean really slow. @zchee could there be an option to disable `input_pattern` and only use `min_pattern_length`?

Its so much more responsive for me without it.

**Comment by zchee** [comment]
@nhooyr Oh... :(
Sorry, I'll reply later. please wait a little.

**Comment by zchee** [comment]
@nhooyr I rough profiled with old `input_pattern` and current `input_pattern`.
- https://github.com/zchee/deoplete-go/blob/280f86890282499eee7a0c2fb1d14ee2e5835a12/rplugin/python3/deoplete/sources/go.py#L28

It did not change much in my environment, but It seems to become certainly slow.

I'll post an additional comment later.

**Comment by nhooyr** [comment]
Actually never mind, I was mistaken, nothing to do with deoplete-go.
