### ISSUE TITLE
Does not support 'github.c...' in import completion

### ISSUE THREAD

**Issue by zchee** [zchee/deoplete-go#46]
Go built-in package is working perfectly.
but, third-party package (e.g. `github.com/tools/godep`, `golang.org/x/tools`).
Caused by dot (`.`) in the domain name.

Ref: 
- https://github.com/zchee/deoplete-go/issues/32#issuecomment-195541918
- https://asciinema.org/a/3xz29k70w2zmi27sg2zugde74

**Comment by nhooyr** [comment]
Wow, this has nothing to do with the regex. its something else.

**Comment by nhooyr** [comment]
I got it, its this line:

``` vim
        m = re.search(r'\w*$', context['input'])
```
