### ISSUE TITLE
Completion not showing up

### ISSUE THREAD

**Issue by daenney** [zchee/deoplete-go#57]
I've set everything up I believe according to the instructions but I can't get completion to show up for any Go package, including the built-in ones.

``` vim
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-go', { 'do': 'make' }

" Deoplete
let g:deoplete#enable_at_startup = 1
set completeopt=longest,menuone

" Deoplete go
let g:deoplete#sources#go#gocode_binary = '/Users/daenney/Development/go/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
```

``` sh
$ /usr/local/bin/pip3 freeze
greenlet==0.4.9
msgpack-python==0.4.7
neovim==0.1.8
wheel==0.26.0
```

``` sh
$ which gocode
/Users/daenney/Development/go/bin/gocode
```

``` sh
$ ps aux | grep gocode
daenney         64824   0.0  0.0 573402468   6348   ??  S     6:04pm   0:00.05 /Users/daenney/Development/go/bin/gocode -s -sock unix -addr 127.0.0.1:37373
```

When I start vim I receive no errors and similarly when I start editing Go files I see no errors showing up anywhere. But I don't get completions either.

**Comment by daenney** [comment]
Whatever it was, this managed to fix itself. I'm still grasping at straws on how to debug these kinds of issues though.

**Comment by zchee** [comment]
@daenney Sorry, I have overlooked this issue.

> I'm still grasping at straws on how to debug these kinds of issues though.

still not showing completion list?

**Comment by daenney** [comment]
Oh yes, the completion lists are fine, everything works now. What I'm wondering about is, if this happens again, how can I go about and try to figure out what caused it?

**Comment by zchee** [comment]
@daenney I'm relieved to hear that :)

What are you using go version? devel?

**Comment by daenney** [comment]
In my case it's Go 1.6.2 on darwin/amd64 (OS X).

**Comment by zchee** [comment]
@daenney Hm,

FYI, Go devel has merged the new binary format (compact binary export format) recently.
https://github.com/golang/go/commit/ae2f54a7718e803fe00ee0e5b83e6c07036ba93f
`gocode` get the completion list parses the binary(`.a` ) in your `$GOPATH/pkg`.
So, if you use the devel, gocode will `PANIC` unless update gocode to the latest.

but, you use 1.6.2. it's not related this issue. :(
If you that problem happen again, Please repost or reopen issue thread.

**Comment by daenney** [comment]
Alright, will do. Thank you for taking the time to respond!
