### ISSUE TITLE
Double [Go] tag in complete list

### ISSUE THREAD

**Issue by dlogvinenko** [zchee/deoplete-go#59]
Not sure if it's deoplete or deoplete-go, but:

Two times [Go] [Go]:

![screen shot 2016-06-06 at 15 29 45](https://cloud.githubusercontent.com/assets/883328/15821947/9bc066b0-2bfb-11e6-832a-a73cab3e6261.png)

**Comment by zchee** [comment]
@vort3x Oh, yes. now I write `note ...` before issue threads \o/

Please update latest? It's has been fixed :)
https://github.com/zchee/deoplete-go/commit/c84e6df86b4e36152ccd33bfce33d6ca4a88867f

**Comment by dlogvinenko** [comment]
Verified :)

**Comment by zchee** [comment]
yeah!
