### ISSUE TITLE
`g:deoplete#sources#go#json_directory`

### ISSUE THREAD

**Issue by kevin70** [zchee/deoplete-go#63]
1. let g:deoplete#sources#go#json_directory = '/Users/kevin/.cache/deoplete/go/darwin_amd64'  --> working
2. let g:deoplete#sources#go#json_directory = '~/.cache/deoplete/go/darwin_amd64' --> not working

why?

**Comment by Shougo** [comment]
`g:deoplete#sources#go#json_directory` does not expand `~`.

**Comment by zchee** [comment]
@weghst Hi, sorry for late reply :(

Yes, and good catch.
Currently, simple `os.path.join`ed that directory path.
https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/deoplete_go.py#L169
I think not user-friendly, so will adding `os.path.expanduser`(correct? forgot) to that line later.
Thanks !

**Edit**: I wonder why not occur my env 😕
...Well, I set `let g:deoplete#sources#go#json_directory = $HOME . '/.cache/deoplete/go/darwin_amd64'`. I had forgotten the case of the setting.

**Comment by zchee** [comment]
@kevin70 As https://github.com/zchee/deoplete-go/commit/6e952846719af1a672f8cbc22347ba3255671d2c commit, it seems fixed to expand problem by the `deoplete.util.expand`.
Now I'll close it, if you still have same error, please re-open this issue or create a new issue thread.

@Shougo Thanks for a deal with it!
