### ISSUE TITLE
g:deoplete#sources#go#sort_class breaks variable/function autocompletion

### ISSUE THREAD

**Issue by dobegor** [zchee/deoplete-go#65]
Please, see [this](https://github.com/Shougo/deoplete.nvim/issues/305#issuecomment-232655888) issue.

**Comment by zchee** [comment]
@dobegor Thanks for create issue.

Hmm... I tested **set** and **not set** `sort_class` variable both case.
Here is screencast: https://asciinema.org/a/79665

# 

Sorry, Do I misunderstand...?

**Comment by dobegor** [comment]
@zchee `os` and `fmt` are not completed during typing them.
I will record my screencast a bit later.
Maybe reach @Shougo in Gitter if he can help you understand and reproduce the issue (I will be able to record screencast tonight, in ~3 hours at least).

**Comment by Shougo** [comment]
@zchee Please test `str` completion.
If `sort_class` is not set, `str` is completed.
But it `sort_class` is set, `str` is not completed.

**Comment by dobegor** [comment]
@zchee https://asciinema.org/a/30l1y4whqq2bbusd5lmhed9xc
Here is my screencast.

**Comment by zchee** [comment]
@dobegor 
Ah! I understand all now. nevermind, You do not need to take the screencast.

~~and, I found causes. If lacking `package` value in `sort_class`, does not completion `str` or etc.~~
~~The immediate workaround is adding `package` value in `sort_class`.~~
Hmm...
Here is my full init.vim. it will work.
https://gist.github.com/zchee/fd7f60ed6c56c2ee8e26c6885486aa10
but indeed, tiny init.vim not works.

Why....

**Comment by zchee** [comment]
@dobegor Thanks for screencast. will watch and debug this problem.

**Comment by dobegor** [comment]
`package` in `sort_class` worked for me, too, thanks.

**Comment by zchee** [comment]
@dobegor really? I was relieved to hear it.
but still not understand all why does not complete if lack package. 
maybe you do not want complete package, So I will continue to debug and fix it.

anyway, It was very valuable information. thanks!!

# 

Also, Sorry for my ugly English :(
Thank you for understanding my mind.

**Comment by dobegor** [comment]
@zchee thank you for the fix and for the awesome plugin, which I use every day in my neovim setup.

**Comment by zchee** [comment]
@dobegor Now fixed this problem! Caused by initializing `class_dict` variable keys. My bad...

> thank you for the fix and for the awesome plugin, which I use every day in my neovim setup.

Very very thanks😭

BTW, I will publish(in 2~3 month at least) neovim remote plugin that fully compatible vim-go written in pure Go.
Look forward to it if you are interested 😃

**Comment by dobegor** [comment]
@zchee nice, people with little-to-zero experience with Vimscript like me would be able to contribute the plugin in Go.
