### ISSUE TITLE
g:deoplete#sources#go#pointer does nothing

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#67]
The setting `g:deoplete#sources#go#pointer` seems to do nothing for me.

https://asciinema.org/a/dbc1pyyactfvz1n6uqqrmsfkh

**Comment by zchee** [comment]
@nhooyr Thanks issue :)
Ok, check it. sec.

**Comment by zchee** [comment]
@nhooyr Hmm, it seems not working :(
I want to debug with that `main.go` file. Could you post that file?

**Comment by nhooyr** [comment]
``` go
package main

import (
    "crypto/tls"
    "flag"
    "fmt"
    "net"
    "os"
    "os/signal"
    "syscall"

    "github.com/nhooyr/log"
    "github.com/nhooyr/toml"
)

var logger *log.Logger

type config struct {
    proxies []*proxy
}

func main() {
    path := flag.String("c", "/usr/local/etc/tlswrapd/config.toml", "path to the configuration file")
    timestamps := flag.Bool("timestamps", false, "enable timestamps on log lines")
    flag.Parse()

    logger = log.New(os.Stderr, *timestamps)

    c := new(config)
    toml.Unmarshal(*path, c)
    if errs != nil {
        for _, e := range errs {
            logger.Print(e)
        }
        os.Exit(1)
    }

    sigs := make(chan os.Signal, 1)
    signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
    go func() {
        <-sigs
        logger.Print("terminating")
        os.Exit(0)
    }()

    logger.Print("initialized")
    for i := 1; i < len(p); i++ {
        go p[i].serve()
    }
    p[0].serve()
}
```

**Comment by zchee** [comment]
@nhooyr Thanks quickly :)

**Comment by zchee** [comment]
@nhooyr Hmm, It will work in my environment :(
What results of `gocode -in main.go autocomplete 249`?

![screenshot 2016-08-10 09 20 18](https://cloud.githubusercontent.com/assets/6366270/17537963/c2737672-5edb-11e6-9258-2c82188d30ac.png)

**Comment by nhooyr** [comment]
```
Found 54 candidates:
  const false 
  const iota 
  const nil 
  const true 
  func append([]type, ...type) []type
  func cap(container) int
  func close(channel)
  func complex(real, imag) complex
  func copy(dst, src)
  func delete(map[typeA]typeB, typeA)
  func imag(complex)
  func len(container) int
  func main()
  func make(type, len[, cap]) type
  func new(type) *type
  func panic(interface{})
  func print(...interface{})
  func println(...interface{})
  func real(complex)
  func recover() interface{}
  package flag 
  package fmt 
  package log 
  package net 
  package os 
  package signal 
  package syscall 
  package tls 
  package toml 
  type bool built-in
  type byte built-in
  type complex128 built-in
  type complex64 built-in
  type config struct
  type error interface
  type float32 built-in
  type float64 built-in
  type int built-in
  type int16 built-in
  type int32 built-in
  type int64 built-in
  type int8 built-in
  type proxy struct
  type rune built-in
  type string built-in
  type uint built-in
  type uint16 built-in
  type uint32 built-in
  type uint64 built-in
  type uint8 built-in
  type uintptr built-in
  var d *net.Dialer
  var logger *log.Logger
  var path *string
```

**Comment by nhooyr** [comment]
Without builtins:

```
Found 10 candidates:
  package flag 
  package log 
  package os 
  package signal 
  package syscall 
  package toml 
  type config struct
  type proxy struct
  var d *net.Dialer
  var logger *log.Logger
```

`proxy` and `d` are from another file in the same package.

**Comment by zchee** [comment]
@nhooyr Hmm...
OK, I will more debug later. please wait a little...

**Comment by zchee** [comment]
@nhooyr Sorry for delay, Do you still have this problem?

**Comment by nhooyr** [comment]
@zchee I'm in the middle of setting up my dev environment again as I clean installed macOS Sierra. So I cannot test this right now. I will try to update this once I have everything set up again.

**Comment by zchee** [comment]
@nhooyr np! I know your situation by gocode issue thread lol

BTW, gocode issue seems to re-write some method? Can I help you?
(**Edit**: because you can't develop by upgrade OS)

**Comment by nhooyr** [comment]
@zchee Don't worry about it, it's a small issue and someone else is already working on it. Thanks for asking though :)

**Comment by zchee** [comment]
@nhooyr :D

**Comment by zchee** [comment]
@nhooyr Was there any progress on this?

**Comment by nhooyr** [comment]
@zchee nope. I'll look into it now, my environment is set up now.

**Comment by nhooyr** [comment]
Yes, it still seems to do nothing. With or without it set, it automatically completes here

```
package main

type Foo struct {
    FooName string
}

func NewFoo() *Foo {
    return &Foo{}
}

func (f *|
```

<img width="1440" alt="screen shot 2016-11-12 at 11 23 31 am" src="https://cloud.githubusercontent.com/assets/10180857/20239260/8601e730-a8ca-11e6-8540-57c50bc0c9af.png">

<img width="1440" alt="screen shot 2016-11-12 at 11 23 48 am" src="https://cloud.githubusercontent.com/assets/10180857/20239261/8601f752-a8ca-11e6-9690-5e2452034594.png">

**Comment by zchee** [comment]
@nhooyr Hmm...
OK, I'll debug it :)

**Comment by Shougo** [comment]
Reproduced.  I will fix it.
