### ISSUE TITLE
is json caching necessary?

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#70]
See nsf/gocode#368.

You can complete unimported  packages now.

**Comment by zchee** [comment]
@nhooyr Yeah, gocode has been unimported package completion. This feature is great.
I also think probably json cache is no longer necessary.

I consider remove json cache system from deoplete-go, but now, I have no time for developing it.
I will more check gocode internal change, and testing deoplete-go.
Sorry, please wait a moment.

**Comment by zchee** [comment]
@nhooyr IIRC, gocode not implement yet the duplicate package issue.(but deoplete-go also use "mixed" method completion)
I want to fix it.

After that, I'll remove json cache or change to (very) optional feature for users who want to any package caching.

**Comment by Shougo** [comment]
I can remove the cache feature.
It should be removed?

@zchee Ping.

**Comment by zchee** [comment]
@Shougo Yeah, now cache feature is overkill. We should remove it. But sorry, I'm little busy... :(

> I can remove the cache feature.

It meaning you remove cache feature instead of me?

**Comment by Shougo** [comment]
> It meaning you remove cache feature instead of me?

Yes, because it is not hard.
But no performance problem?

**Comment by Shougo** [comment]
And to remove json dependency.

**Comment by Shougo** [comment]
Related issue: https://github.com/zchee/deoplete-go/issues/93

**Comment by zchee** [comment]
@Shougo
> But no performance problem?

Yes, gocode already provide almost same feature. It call `unimported-packages`. e.g. not write `fmt` to import section, but can complete `fmt` methods.
But that gocode feature is not perfect. That's why I added json cache feature. gocode still not fixed, but I think remove deplete-go json cache feature is no problem.

> And to remove json dependency.

Short answer is no.
gocode returns the json format completion list. So deoplete-go still need json dependency.

**Comment by Shougo** [comment]
OK.

**Comment by Shougo** [comment]
Done.

**Comment by notjrbauer** [comment]
I really relied on my json cache directory, even with the update to gocode. Would it hurt to leave it optional again?

**Comment by notjrbauer** [comment]
Nevermind! I needed to `gocode set unimported-packages true`.

**Comment by Shougo** [comment]
OK
