### ISSUE TITLE
Support for gocode socket

### ISSUE THREAD

**Issue by LK4D4** [zchee/deoplete-go#74]
I would like to have an option for specifying gocode unix-socket. I'd use it for [client side autocompletion](https://github.com/mdempsky/gocode/pull/21), but it looks like an overall useful option.
Let me know what do you think about this.
Thanks!

**Comment by zchee** [comment]
@LK4D4 Hi, thanks for issue.

I know https://github.com/mdempsky/gocode change (just in case, that's fork version from nsf/gocode).

Sorry, I do not understand yet you said meaning.
It's like support connect gocode socket on Python, and send rpc request to directly?
Or, you want to both support two gocode version?

---

off topic: I always using container technology for several project. Thanks for great works :)

**Comment by LK4D4** [comment]
@zchee @mdempsky version is compatible with nsf version. Original has -sock flag too, it's just slightly overloaded in fork - if it's set to "none" then  it doesn't spawn server, but just does completion directly in client. From client point of view it's same - you just call gocode binary which returns completion suggestions. 
So, I'd love to have something like g:deoplete#sources#go#gocode_sock which is passed to gocode binary as "-sock" argument in Popen.

**Comment by zchee** [comment]
@LK4D4 Oh! understand.
Yeah, I almost know compatibility and no compatibility points. I was researched mdempsky's internal source.

So, you usually use mdempsky version(FYI, I use nsf ver.), and needs add `-sock none` arg.
https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/deoplete_go.py#L210-L217

like

``` python
        self.sock = vars.get('g:deoplete#sources#go#gocode_sock', False)
        .
        .
        .
        args = ['-f=json', 'autocomplete', buffer.name, str(offset)]
        if self.sock:
                args += '-sock ' + self.sock
        process = subprocess.Popen(
            [self.find_gocode_binary(), args],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=True,
            env=env)
```

?

**Comment by LK4D4** [comment]
@zchee Yes, indeed! That's what I had in mind. 
I've switched to mdempsky version recently because I understand it internals slightly better and did not notice any problems. 
Thanks!

**Comment by zchee** [comment]
@LK4D4 I totally understand : ) Okay, will adding that implements.

After added, send ping to you. thanks :)

**Comment by zchee** [comment]
@LK4D4 Now @tweekmonster works this pull request https://github.com/zchee/deoplete-go/pull/73
Maybe that my sample conflict.

After merged it, I will start the develop.
