### ISSUE TITLE
No autocompletion for vendored packages

### ISSUE THREAD

**Issue by nrvnrvn** [zchee/deoplete-go#75]
Hi!

I don't get autocompletion for vendored packages.
Whereas any system and `go get`ed packages are fully supported.

**Comment by zchee** [comment]
@nicorevin Hmm...
deoplete-go use `gocode` result directly. and, I don't understand yet your situation.
What 

> Whereas any system and go geted packages are fully supported.

Just in case(I think you already know), `gocode` uses compiled `.a` file without `gocode set autobuild true`.

What situations occurred this problem?

**Comment by nrvnrvn** [comment]
When I was creating this issue I was not aware of `gocode` using `.a` files for the autocompletion search. I learnt it a little bit later ;)

See also https://github.com/nsf/gocode/issues/381

**Comment by zchee** [comment]
@nicorevin ah, you want to `import` completion for vendoring package? I misunderstood.
And, yeah, also gocode always use `.a`, so needs `go install` :)
