### ISSUE TITLE
No autocompletion for go keys

### ISSUE THREAD

**Issue by ghost** [zchee/deoplete-go#76]
when I edit a new go files,there is no autocompletion for go keys.

**Comment by zchee** [comment]
@ahlks Hi, thanks issue :)

Just in case, it means no completion after `go|` (`|` is cursor)?  or not completion any word?

**Comment by ghost** [comment]
@zchee 
It is not completion any word. It similar is deoplete-go isn't startup

**Comment by Shougo** [comment]
Please upload minimal init.vim.
And gocode is already installed?

**Comment by ghost** [comment]
@Shougo 
Gocode is already installed.

this is my init.vim:

"""""""""""""""""""""""下面时插件设置"""""""""""""""""""""''"""

call plug#begin('~/.config/nvim/plugged')

" go
Plug 'Shougo/deoplete.nvim'
Plug 'fatih/vim-go', {'for': ['go'] }
Plug 'zchee/deoplete-go', {'for': ['go'] }

call plug#end()            

" vim-go
let g:go_bin_path = expand("$HOME/.config/nvim/vim-go-tools")
au FileType go nnoremap gf :GoReferrers<cr>
au FileType go nnoremap gr :GoRename<cr>
au FileType go nnoremap gc :GoCallers<cr>
au FileType go nnoremap gs :GoCallstack<cr>
au FileType go nnoremap gi <Plug>(go-implements)
"let g:go_auto_sameids=1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

"deoplete
let g:deoplete#enable_at_startup = 1
inoremap <expr><TAB>  pumvisible() ? "<C-n>" : "<TAB>"

"deoplete-go
let g:deoplete#sources#go#gocode_binary = '$HOME/.config/nvim/vim-go-tools/gocode'
let g:deoplete#auto_complete_delay = 25
"let g:deoplete#sources#go#use_cache = 1
"let g:deoplete#sources#go#json_directory = '$HOME/.config/nvim/plugged/deoplete-go/data/json/1.7/linux_amd64'

**Comment by Shougo** [comment]
I get the problem.
deoplete-go does not expand `g:deoplete#sources#go#gocode_binary` and `g:deoplete#sources#go#json_directory` paths.
So it fails.
Note: deoplete-go should print error messages though.

**Comment by Shougo** [comment]
@zchee I have added expand() function in util.py.  Please use it.

**Comment by zchee** [comment]
@ahlks I was committed used `expand` feature.
Maybe already support `$HOME` or etc.
Could you try the latest master?

@Shougo Thanks for the deal with expand issue, and sorry for the delay of implementation.

**Comment by zchee** [comment]
@ahlks Ah, but it seems to nvim does not expand $HOME if included the quote(`'`).
Maybe the better setting is below.

``` vim
let g:deoplete#sources#go#gocode_binary = $HOME . '/.config/nvim/vim-go-tools/gocode'
let g:deoplete#auto_complete_delay = 25
.
.
```

**Comment by ghost** [comment]
@zchee Tanks for your help, I had use it and it work well.
