### ISSUE TITLE
cannot set propose-builtins to false

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#83]
If I run `gocode set propose-builtins false` and then start neovim, when autocomplete runs in a Go file, `propose-builtins` becomes automatically set to true again.

If I run `gocode set propose-builtins false` after neovim is already running and has already autocompleted a Go file, then `propose-builtins` is not changed.

Seems like deoplete-go is modifying the value on startup.

**Comment by svanharmelen** [comment]
@nhooyr do you use vim-go? As I know vim-go's defaults are configuring gocode settings.

Think you can disable that, but not sure. Should be in the vim-go docs.

**Comment by nhooyr** [comment]
Ah yes I do, `let g:go_gocode_propose_builtins = 0` fixes it.
