### ISSUE TITLE
autocomplete candidate not expection

### ISSUE THREAD

**Issue by ghost** [zchee/deoplete-go#84]
It is not expection when I donit set GOPATH, but is normal after I set GOPATH.

**Comment by nhooyr** [comment]
Do you mean exception? If so, can you post the entire error?

**Comment by ghost** [comment]
@nhooyr  No error, but not the candidate I want

**Comment by nhooyr** [comment]
It's unclear what you mean. Could you be more specific? What is the candidate you want?

**Comment by ghost** [comment]
@nhooyr 
like this, if do not set GOPATH,  complete like picture 1;  if set, picture 2
1:
![20161118173312](https://cloud.githubusercontent.com/assets/20379044/20425525/eba5116c-adb5-11e6-901c-1b5612a4144c.png)
2:
![20161118173430](https://cloud.githubusercontent.com/assets/20379044/20425546/fec28e64-adb5-11e6-91e8-e585ab467e19.png)

**Comment by nhooyr** [comment]
You have to set $GOPATH, otherwise how will gocode know how to complete the code?

**Comment by Shougo** [comment]
I think @ahlks said `deoplete-go should print warning if users don't set $GOPATH`

**Comment by zchee** [comment]
@nhooyr @Shougo Thanks for comment :)

@ahlks Ah, If want to `deoplete-go should print warning if users don't set $GOPATH` , That user also can't `go get` if don't set the `$GOPATH`  until go1.8.
IIRC go1.8 will automatically set `$GOPATH` to `$HOME/go` if not set, So it might changes `gocode` behavior.
However, It remains the env which is essential for Go language. I think "displays the error message" is not the scope of deoplete-go.

**Comment by ghost** [comment]
@nhooyr @Shougo @zchee  Thanks
I understand.
When use neocomplete in vim, it is the same either set or not. So I mistakenly think deoplete-go is the same.

**Comment by Shougo** [comment]
This is closable?

**Comment by zchee** [comment]
It seems good to close this thread.
Close.
