### ISSUE TITLE
nvim freezes on deoplete-go init

### ISSUE THREAD

**Issue by svanharmelen** [zchee/deoplete-go#86]
If I remove lines 103 until 111 from this [commit](https://github.com/zchee/deoplete-go/commit/c97ae5abf8b992f67685834fec4a71b0d9546b6d#diff-47c24d9450107a86b2ea7a4961f13f5c) everything works as expected again.

**Comment by svanharmelen** [comment]
To be more precise, things hang on this command until I kill gocode:

```
self.get_complete_result(self.buffer, context, kill=True)
```

**Comment by Shougo** [comment]
Ping @zchee 

@svanharmelen Please upload minimal init.vim and the sample code.
I will check it.

**Comment by zchee** [comment]
@svanharmelen Oh, really? I haven't that problem. Hmm...
Anyway, I want to minimal init.vim too.

@Shougo Thanks ping.

**Comment by svanharmelen** [comment]
@Shougo @zchee it's very hard to describe how this fails so I'm debugging it myself... I found that if I reopen a saved session with 3 windows, it **sometimes** creates a process for each window?

![image](https://cloud.githubusercontent.com/assets/4171547/20832002/05dfba78-b888-11e6-9e05-852cfd0ffce4.png)

I tried this by closing on window and reopen the session again and this time it only had 2 of the same processes. So somehow it spins the same process multiple times which causes the hang/lockup it seems.

Any pointers on how to move forward?

**Comment by zchee** [comment]
@svanharmelen Ah, maybe understands that's situation. If `on_init` more than once call, gocode might be a freeze.

I think the solve way is calling `on_init` only once with fix deoplete-go or any use deoplete core feature, or checks `gocode` unix socket for whether the already launched `gocode` daemon. (and remove `kill=True` if launched)
Or, `gocode` is very fast even if without AST cache, so remove `on_init` from deoplete-go.

**Comment by svanharmelen** [comment]
@zchee I updated the comment a little as it seems that the `on_init` is triggered multiple times, only when I start switching windows as soon as the session has loaded.

But that does not seem the be the issue as in that case the processes would have different autocomplete filenames and offsets (all windows display different files).

So when I do not switch windows after opening the session I see the `on_init` is only called once, but still I see multiple of the same process being started with the same autocomplete filename and offset (as shown in the previous screenshot).

Personally I do not think the caching calls make things noticeable faster, so I would delete all the dummy calls that are only added for the initial caching (in both the `on_init` and `on_event` functions).

**Comment by zchee** [comment]
@svanharmelen Thanks for a very detailed comment :) I'll check it out later.

But yeah, `gocode` is very faster than other languages parser. I will debug it, but maybe better to delete dummy caching.(also json cache - it's buggy :P)

**Comment by svanharmelen** [comment]
Thanks. And indeed I don't use any of the caching stuff... Things are fast enough without it IMHO :wink:

**Comment by zchee** [comment]
@svanharmelen yeah, basically json cache for no imported package completion. but gocode has been implemented this feature. but return mix-in method if duplicate stdlib package name.
I want to fix it on gocode core code. after that, will json cache also remove.

**Comment by svanharmelen** [comment]
@zchee any progress on this? Thx!

**Comment by zchee** [comment]
@svanharmelen Ah, just forgot. very sorry...😱
I'll fix it. (means, remove `on_init` only)

**Comment by svanharmelen** [comment]
That would be great, thanks!

**Comment by zchee** [comment]
@svanharmelen Just a question and just in case,
Do you think good as to remove both the `on_init` and `on_event` functions?

**Comment by svanharmelen** [comment]
Yeah, I would remove both the `dummy` calls. Tested this locally and do see any downsides (also not any noticeable drawback in speed)...

**Comment by zchee** [comment]
@svanharmelen OK, got it. I'll remove it now :)

**Comment by zchee** [comment]
@svanharmelen Done :)

**Comment by svanharmelen** [comment]
Cool, thx @zchee!
