### ISSUE TITLE
import error: cannot import name 'expand'

### ISSUE THREAD

**Issue by xpressivecode** [zchee/deoplete-go#89]
I'm not sure what information you would need in order to help troubleshoot this? I've just installed nvim, the phython client, deoplete and deoplete-go. 

It says the file in question is: rplugin/python3/deoplete/sources/deoplete_go.py, line 9. 

"ImportError: cannot import name 'expand'

**Comment by zchee** [comment]
@XpressiveCode It seems to your deoplete.nvim is the old version.
`expand` is added deoplete.nvim at
https://github.com/Shougo/deoplete.nvim/commit/bfa9703e50d16d6e2d45b765b1a94885c21ef335

Could you update deoplete.nvim?

**Comment by xpressivecode** [comment]
Thanks for the quick response, that did it!
