### ISSUE TITLE
deoplete-go can't deal with files open with Netrw

### ISSUE THREAD

**Issue by glacambre** [zchee/deoplete-go#90]
I recently tried to open a file over the scp:// protocol which is handled by Vim's "Netrw" plugin. When trying to autocomplete a word, the message```[deoplete] gocode panicked``` is shown.
Here are the steps to reproduce the bug when deoplete and deoplete-go are loaded in your vimrc:
```
nvim scp://server//tmp/tmp.go
:set ft=go
a
fmt
```
This will open a file with Netrw, set the filetype to "go", enter insert mode and type "fmt". The message
```
match 1 of 6
[deoplete] gocode panicked
```
will then be shown and the autocompletion popup won't be shown.
I believe this is a bug with deoplete-go because other autocompletion plugins (deoplete-jedi for example) do not have this problem.

**Comment by Shougo** [comment]
The file in the remote server is not supported.
And it is hard to test.

**Comment by Shougo** [comment]
I will fix the problem.
