### ISSUE TITLE
automatically insert parentheses when completing a function

### ISSUE THREAD

**Issue by nhooyr** [zchee/deoplete-go#92]
It'd be cool if when I complete a function like `log.Fat|`, (`|` is cursor) it completes it to `log.Fatal(|` and then I can continue typing.

**Comment by nhooyr** [comment]
Ah, I can already do this with `call deoplete#custom#set('_', 'converters', ['converter_remove_overlap', 'converter_truncate_abbr', 'converter_truncate_menu', 'converter_auto_paren'])`

**Comment by zchee** [comment]
:D
