### ISSUE TITLE
ValueError: Expected object or value

### ISSUE THREAD

**Issue by tiborvass** [zchee/deoplete-go#96]
@zchee Every time I open a blank new file and write `pa` in insert mode (in order to write `package main`) I have the following error in the vim bar:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/tibor/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", lin
e 124, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/tibor/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go
.py", line 110, in gather_candidates
[deoplete]     context, getlines(self.vim), bufname)
[deoplete]   File "/Users/tibor/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go
.py", line 260, in get_complete_result
[deoplete]     return loads(stdout_data.decode())
[deoplete] ValueError: Expected object or value
[deoplete] Could not get completions from: go.  Use :messages for error details.
```

**Comment by zchee** [comment]
@tiborvass Thanks issue.
Sorry, now I'm in the hospital, so difficult to fix and debug, but I will check it.

**Comment by tiborvass** [comment]
@zchee oh! I wish you the best! Health first, projects second ;) Good luck

**Comment by zchee** [comment]
@tiborvass I'm very happy about your words :)
Thanks!!

**Comment by zchee** [comment]
@tiborvass Sorry for the late reply.
I'm back. I'll debug and fix this problem. Thanks for using deoplete-go.

**Comment by zchee** [comment]
@tiborvass BTW, it seems to you using vim-plug plugin manager.
FYI, I use [Shougo/dein.vim](https://github.com/Shougo/dein.vim) and set lazy load. actually, add deoplete-go to `&runtime` is `go` filetype only. If that situation, not reproduced(maybe, on daily coding).
Maybe related to load plugin timing. Are you use vim-plug lazyload feature?

**Comment by LK4D4** [comment]
I have the same problem. I tried to disable lazy-load and still can reproduce.

**Comment by zchee** [comment]
@LK4D4 Thanks for reports. Hmm... I'll try to debug.
Just in case, @tiborvass said the situation is below?

```console
$ ls test.go
ls: cannot access 'test.go': No such file or directory
$ nvim test.go
# in Neovim...
```
```go
pa|
```

**Comment by tiborvass** [comment]
@zchee yes I still have that issue in that situation. And thanks for looking into it! Hope you're better!

**Comment by zchee** [comment]
@tiborvass Thanks. and OK, not reproduced with use the dein.vim.
I'll try to debug and fix it for users who uses other plugin managers such as vim-plug.

> Hope you're better!

:D

**Comment by zchee** [comment]
@tiborvass @LK4D4 I added Dockerfile for the clean test environment for now.
See [dockerfiles/Dockerfile@014cdf0](https://github.com/zchee/deoplete-go/blob/014cdf0b31c6b6e54d9c6f5a1a69efc2e0f23516/dockerfiles/Dockerfile) and run:

```sh
docker build --rm -t zchee/deoplete-go -f dockerfiles/Dockerfile .
# test for exist file
docker run --rm -ti zchee/deoplete-go nvim test.go
# test for **not** exist file
docker run --rm -ti zchee/deoplete-go nvim test2.go
```

But not reproduced :(
Do you have any idea for reproducing?

**Edit**: fix commit hash to latest.

**Edit**:
- deoplete.nvim was revision locked Shougo/deoplete.nvim@90d93201044d6210091cd3786a720d06429afbe7 for now.
- deoplete-go was revision locked 3c8a18663683ff97fb99b7045265b399ee86a834 for now.

**Comment by divan** [comment]
I have the same issue. MacOS X 10, nvim NVIM v0.2.0-779-g58b5e14, latest vim-go and deoplete.

Anytime I press ^X^O to autocomplete I get this error.

**Comment by tiborvass** [comment]
This is not really a deoplete-go issue, but a gocode issue.

If anything, deoplete-go could be more helpful in showing the error message from the output (both stdout and stderr) of the gocode tool, which in this case should have shown a nil dereference panic stacktrace.
